### ISSUE TITLE
Eliminate White Background on Resizing Window.

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#1009]
There was a long standing issue with Electron apps that would result in resizing windows creating a white laggy trace behind them. I believe some people have figured out the solution - you can look at VSCode Insiders (they do not have the laggy white trace).

**Comment by badosu** [comment]
@jordwalke I can't reproduce this issue, do you know if this is specific to a certain configuration?

**Comment by bryphe** [comment]
I just tried it on Windows - it didn't repro for me at first, but I had turned off 'Animate windows while resizing' - once I turned that on I could see the issue:
![resize-windows](https://user-images.githubusercontent.com/13532591/33180144-9e5fb086-d020-11e7-8d97-9d526fcd925a.gif)

There are a few background issues with Electron apps - resizing is one (electron/electron#9608) 

One quick solution from electron/electron#10801 is to use the background color of the app, so at least it matches instead of being glaring white. Checking the Insider's build of VSCode is a good idea - I'm curious if they found a more general way to solve the problem, or if they are using the match-background-color strategy.

I believe this also relates to the blank white screen being shown on startup for a split second (in some cases) - #355

**Comment by jordwalke** [comment]
I seem to recall that the background-color matching trick might require a restart when changing color schemes. Is it dynamically adjustable once the app starts up? Maybe that's why VSCode seems to require restarts for changing themes.

**Comment by jordwalke** [comment]
[Here's a blog post](https://www.christianengvall.se/electron-white-screen-app-startup/) detailing how setting the background color does fix the white flash on startup. The downside is that you have to know ahead of time what the colorscheme will be.

One trick could be, whenever switching colorschemes, have Oni record the color of Vim's background into `~/.oni/.recentSettings` or something, and consult it upon startup. The last used background color when shutting down is likely a 98% accurate indication of what the background color will be upon starting back up.

However, I think this doesn't solve the resizing - which might require a reloading of the entire window. VSCode insiders has definitely solved it though.
