### ISSUE TITLE
Integrated a new c/c++ language server: cquery

### ISSUE THREAD

**Issue by saibing** [onivim/oni#1016]
I'm try a new c/c++ language server: [cquery](https://github.com/jacobdufault/cquery)

CQuery is a Low-latency language server for large C++ code-bases, powered by libclang. It is much more powerful than clangd.

But I ran into some trouble that cquery need add some initializationOptions:

```json
{
        "initializationOptions": {
                "cacheDirectory": "/tmp/cquery",
		"resourceDirectory": "yourCQueryDirectory/clang_resource_dir"
        }
}
```
[How to use cquery with LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/wiki/cquery)

May be Oni need to support config language server's initializationOptions?

**Comment by bryphe** [comment]
Thanks for logging the issue, @saibing !

Yes, unfortunately our configuration doesn't support this currently... But it would make sense to have something like this, ie:
```
"language.cpp.languageServer.initializationOptions": {
                 "cacheDirectory": "/tmp/cquery",
		"resourceDirectory": "yourCQueryDirectory/clang_resource_dir"
}
```

Will use this to track setting the `initializationOptions`.

**Comment by bryphe** [comment]
A good place to start looking is here:
https://github.com/onivim/oni/blob/45f51c59b40dab399f96f2476e9040ee75ee725e/browser/src/Services/Language/LanguageConfiguration.ts#L99

Which is the code responsible for taking the configuration settings and handing them off to the language client.

**Comment by MaskRay** [comment]
See https://github.com/autozimu/LanguageClient-neovim/wiki/cquery 
`"resourceDirectory"` is auto detected and can be removed now.

**Comment by MaskRay** [comment]
I'd like to ask how you would like to detect the project root. When there are subpackages, the root  `compile_commands.json` contains entries for subproject files and you do not want files in subprojects to be associated with subprojects, but rather the root project.

```
proj
 compile_commands.json
 .git
 third_party
  proj0
   .git
   a.cc       // you want this file to be associated with the root project
  proj1
   .git
```

Sorry for pasting the link of the Emacs lsp-mode discussion thread. But they have the same issue
https://github.com/emacs-lsp/lsp-mode/issues/293 and I think it is beneficial to draw on the wisdom of the masses

**Comment by saibing** [comment]
@MaskRay 
Thank you very much

Now I can solve this problem by add follow config into config.tsx
```ts
    "language.cpp.languageServer.arguments": ["--init", '{"cacheDirectory": "/tmp/oni_cquery"}'],
```

**Comment by MaskRay** [comment]
For cquery users, you may consider ccls. It differs a lot from cquery now (5000 lines fewer, fewer third-party dependencies, IMO simpler but better pipeline, slightly better memory index). You can find some rationale for the fork at https://github.com/MaskRay/emacs-ccls/issues/1

https://github.com/MaskRay/ccls/wiki/Getting-started

**Comment by MagB93** [comment]
@free-easy  
I'm having a similar issue with the configuration of cquery for oni. Currently this is my config for
for cquery:
`    "language.cpp.languageServer.command": "/usr/bin/cquery",
    "language.cpp.languageServer.rootFiles": ["compile_commands.json"],
    "language.cpp.languageServer.arguments": ["--init", '{cacheDirectory": "/home/magb/.cache/cquery"}']
`

I'm receiving the same error in the console as @free-easy. @saibing could you provide your configuration? And maybe a mention of cquery in the wiki would be nice.

**Comment by feltech** [comment]
I just gave ccls (fork of cquery) a go, after clangd failed miserably, giving lots of spurious errors (despite the c++ command that clangd was supposedly running, evidenced from Oni's STDERR log, giving no errors when run independently...).

ccls, on the other hand, is working beautifully.  My Oni configuration is as below (with the binary path altered for brevity)
```
    "language.cpp.languageServer.command": "/path/to/ccls",
    "language.cpp.languageServer.arguments": [
        "--log-file=/tmp/cc.log"
    ],
    "language.cpp.languageServer.rootFiles": [
        "compile_commands.json"
    ],
```
Initially it didn't work, so I added the `--log-file`.  That pointed me to a failure to find `compile_commands.json`, because it was looking in my `src` directory (the location of the first source file I opened) rather than the project root.  The logs also hint at a `compilationDatabaseDirectory` that can be passed as part of the `--init` option.  I wasn't keen on setting that to a fixed directory, since I would have to change Oni config when switching projects.  Then I noticed other language servers are configured with a `language.<lang>.languageServer.rootFiles` option in Oni.  I added that line, and voila! ccls working nicely.

Oh, there was one other custom thing I did.  I modified the build of ccls to use clang 7 (the current master defaults to clang 6), but I doubt that would make much difference to Oni integration.

**Comment by badosu** [comment]
@feltech Would you mind adding your lsp config to https://github.com/onivim/oni/wiki/Language-Support#cc?

**Comment by feltech** [comment]
OK, done.  I didn't realise we could edit the wiki so easily!  I'll have to think of some more useful stuff to add...

**Comment by feltech** [comment]
Also, the `No grammar found for language: cpp` is a separate issue.  Oni does not come bundled with a TextMate grammar file for c++.  I don't actually know what these files are supposed to do(?), but the warning was bothering me. So I lifted [one from Theia-IDE](https://github.com/theia-ide/theia/blob/master/packages/cpp/data/cpp.tmLanguage.json), put it in `oni/extensions/cpp/syntaxes` (to fit with the existing grammar files), and referenced it in my config with 
```
"language.cpp.textMateGrammar": "/path/to/oni/extensions/cpp/syntaxes/cpp.tmLanguage.json"
```
That stopped the warning in the console, at least.

**Comment by Akin909** [comment]
@feltech re. the grammar issue the text mate grammars allow oni use textmate syntax highlighting for different file types which tend to be richer than vim ones, a good source tends to be vscode or atom but any good one will do, you should see better highlighting with that change? also we are actually trying to amass as many bundled grammars as possible as they tend to be quite small files and massively improve the appearance of different file types

**Comment by free-easy** [comment]
@Akin909 Does this mean that Oni has its own engine for syntax highlighting, instead of the (slow) engine provided by Vim/Neovim? Does it run in another thread?

**Comment by Akin909** [comment]
@free-easy we use textmate grammars to parse and tokenize a file this happens in js (on the main thread atm although were looking at offloading this using `webworkers` but thats still a WIP see things like #2617), I don't actually know how the tokenization (via `vscode-textmate`) compares to vim's regex engine, but we then use nvim's msgpack api to tell nvim to highlight the tokens we've parsed, all in all I'm not sure how it all compares, but on oni's side of things we definitely have room to optimise the highlighting.

As a random side note/ tangent I personally am quite keen on looking into adding an option to use [`treesitter`](https://tree-sitter.github.io/tree-sitter/) (created by one of atoms developers and now being trialled in atom) instead of textmate for syntax highlighting, theres a couple of good talks by the author on how it differs but the long and short is it seems to provide more relevant and consistent highlighting than textmate but is still fairly new

**Comment by feltech** [comment]
Some more on ccls/cquery with Oni... I was a bit premature in my optimism.  In particular, completions are a pain.  I gave up on ccls and moved to cquery to see if that was any better, but they seem to suffer the same problems.  In particular I have discovered (so far):

* Critically: Oni's language server integration completely hangs when requesting `completionItem/resolve` from cquery.  The server simply does not respond to the request, so the promise is never fulfilled and the request queue just keeps building up forever. 
The fix is simple, however.  Oni already queries for the language server "capabilities", and cquery responds saying it doesn't support  `completionItem/resolve` (`completionProvider.resolveProvider` is `false`), but Oni ignores them when it comes to `completionItem/resolve`.  PR incoming.
* Oni only supports single trigger characters for the completion popup, i.e. `.` works, but not `->` nor `::`.  You can use `>` and `:` as a workaround, but it's a bit weird.
* cquery requires more configuration that ccls - it just quits out unless you give it a cache directory to use.  My config for cquery looks like (most of it is for logging, the key bit is the `--init`):
```
    "language.cpp.languageServer.command": "/path/to/cquery",
    "language.cpp.languageServer.arguments": [
        "--log-file=/tmp/cquery.log", `--init={"cacheDirectory": "/tmp/cquery.cache"}`
        "--record", "/tmp/cquery"
    ],
```

**Comment by feltech** [comment]
Updated wiki with config for cquery and a warning about code completion.

**Comment by MaskRay** [comment]
> Some more on ccls/cquery with Oni... I was a bit premature in my optimism. In particular, completions are a pain. I gave up on ccls and moved to cquery to see if that was any better, but they seem to suffer the same problems. In particular I have discovered (so far):
> 
> * Critically: Oni's language server integration completely hangs when requesting `completionItem/resolve` from cquery.  The server simply does not respond to the request, so the promise is never fulfilled and the request queue just keeps building up forever.
>   The fix is simple, however.  Oni already queries for the language server "capabilities", and cquery responds saying it doesn't support  `completionItem/resolve` (`completionProvider.resolveProvider` is `false`), but Oni ignores them when it comes to `completionItem/resolve`.  PR incoming.
> * Oni only supports single trigger characters for the completion popup, i.e. `.` works, but not `->` nor `::`.  You can use `>` and `:` as a workaround, but it's a bit weird.
> * cquery requires more configuration that ccls - it just quits out unless you give it a cache directory to use.  My config for cquery looks like (most of it is for logging, the key bit is the `--init`):
> 
> ```
>     "language.cpp.languageServer.command": "/path/to/cquery",
>     "language.cpp.languageServer.arguments": [
>         "--log-file=/tmp/cquery.log", `--init={"cacheDirectory": "/tmp/cquery.cache"}`
>         "--record", "/tmp/cquery"
>     ],
> ```

The issue is that ccls/cquery do not set `completionProvider.resolveProvider`. oni should not try resolving completion items (they are already resolved in the `textDocument/completion` responses)

>  In particular, completions are a pain.

If you find snippets `$1 $2` inserted, you may check https://github.com/MaskRay/emacs-ccls/issues/15
I've written something about expected responses in the thread.

> Oni only supports single trigger characters for the completion popup, i.e. . works, but not -> nor ::. You can use > and : as a workaround, but it's a bit weird.

If this is ever an issue, there must be something wrong on oni's side. They work pretty well in other language clients (lsp-mode, LanguageClient-neovim, vscode-languageclient)

**Comment by feltech** [comment]
> The issue is that ccls/cquery do not set completionProvider.resolveProvider

Like I day, I found that cquery _does_ set it, and sets it to `false`, but Oni ignores it.  This is fixed in the PR above.

> > Oni only supports single trigger characters for the completion popup, i.e. . works, but not -> nor ::. You can use > and : as a workaround, but it's a bit weird.
>
> If this is ever an issue, there must be something wrong on oni's side. 

Yeah I found the code in Oni responsible for that and started work on a fix, but the logic is a bit fiddly, to say the least!

**Comment by MaskRay** [comment]
@feltech For the single character `triggerCharacters`: https://github.com/Microsoft/language-server-protocol/issues/138

The client send `>` as `triggerCharacter` in `textDocument/completion`. While it can check its own buffer lines and send more characters, or the server can check its view of the buffer, but the specification or the reference implementation (vscode) does not do the sensible thing.
