### ISSUE TITLE
Large files open and then crash

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1064]
I have a few largish text files (60+ MB), that I open, see the contents without any colourscheme etc, and then it is closed a moment later and replaced with the "Uh Oh Neovim isn't installed!" screen.
If I instead launch Oni and then open the file after Oni is open, the files load fine.

I assume the flashing with no colourscheme is deliberate to make loading faster, since I see it on an all files.
The crashing I'm assuming it is due to a timeout or perhaps Neovim not responding for a moment as the file loads?

**Comment by bryphe** [comment]
Interesting, thanks for catching this!

I was able to reproduce on Windows. Seems like something weird is happening - I wonder if due to the colorscheme changes, there is some timing change in loading that is causing this.

> I assume the flashing with no colourscheme is deliberate to make loading faster, since I see it on an all files.

Yes, ideally we wouldn't have this flash, though. It seems like we render first with the default colorscheme, and then render again after the colorscheme has changed. Not ideal - IMO it should wait for  Neovim to start (completely), then set the colorscheme, and then finally render the UI, to minimize that flicker.

**Comment by bryphe** [comment]
Strange, it seems that if we remove our `BufEnter` event from firing from Neovim -> Oni, the problem goes away. I wonder if this started with the upgrade to Neovim 0.2.2?

In any case, one option I'm thinking about for fixing it, is instead of opening the files directly via arguments to Neovim, we wait for Neovim to load, and _then_ open the files (following a similiar code path to the menu option that you added for opening the files).
