### ISSUE TITLE
Architecture independent release not available on 0.2.18

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1065]
Could not find `https://github.com/onivim/oni/releases/download/v0.2.18/Oni-0.2.18-linux.tar.gz`.

Also, it's not obvious which of the releases should be chosen for x86_64 as there is not `tar.gz` file available for this arch.

**Comment by bryphe** [comment]
Thanks for the heads up here, @badosu !

So it looks like our upgrade of `electron-builder` caused a change in our filename for the linux package - including the architecture.

It seems, unfortunately, that we never actually had an architecture-independent package - it was always `x64`, just didn't have the architecture in the filename.

So we have a couple of options here:
- __Option 1:__  We could make the AUR package x64 only, setting the `arch` setting in our `PKGBUILD` to reflect that, and point to `Oni-0.2.18-linux-x64.tar.gz` I'd imagine this is reasonable, since no-one complained about it not working on x86/ia32...
- __Option 2:__ We could switch fix our configuration such that we output `Oni-0.2.18-linux.tar.gz`, which is the same we had for other builds. Downside is it doesn't seem like it would work in `x86` architectures (which it never did)
- __Option 3:__ We could update our build script to build both `x86` and `x64` architectures, and then pick the right one based on the current architecture.

I'm not sure what the best option is - __Option 2__ would be the simplest IMO and behave similiarly to how the other releases did. @badosu , what do you think?

**Comment by badosu** [comment]
Assuming x64 is what is referenced on arch as x86_64 and that this was always the target architecture, it's safe to assume that this should be a x86_64 package only.

If users actually want another architecture supported we must support it explicitly and actually make it be a supported target.

I am in favour of `Option 1`.

Let me know your decision and I'll update the package.

**Comment by bryphe** [comment]
__Option 1__ sounds good to me too - it's essentially the same behavior as previous releases. As you mentioned we can always pivot if we get feedback.

Thanks @badosu for your work maintaining our AUR package!

**Comment by badosu** [comment]
Done.
