### ISSUE TITLE
Visual artifacts below searched words

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1083]
See the underline below the words searched, they persist even after `:nohlsearch`:

![screenshot from 2017-12-06 13-43-04](https://user-images.githubusercontent.com/347552/33670146-85cd50bc-da8b-11e7-9672-1f54994199b6.png)

**Comment by bryphe** [comment]
Interesting, looks like this might be subpixel rendering issues.

We do some work to align boundaries of rectangles to the nearest pixel here:
https://github.com/onivim/oni/blob/23822545b4aaff55c61ac58a5b7e8a4906d1f3e3/browser/src/Renderer/CanvasRenderer.ts#L259

But only for the horizontal (`x`) coordinate... potentially we need to do a similiar normalization for the `y` coordinate as well.

**Comment by Akin909** [comment]
@badosu I'm currently looking at fixing this bug, but personally haven't really been able to reproduce it as I think it likely relates to the font you use and its font size, In order to test out the fix could I possibly get details about the font you are using in the screen shot and what the font size is?

**Comment by CrossR** [comment]
I'm able to reproduce this with the default Oni font settings, opening any Oni .ts file, pressing `*` on `import`, and then using the `:nohlsearch` command.

![image](https://user-images.githubusercontent.com/10038688/34537861-e9497232-f0c1-11e7-9823-a35c20ff1793.png)

**Comment by Akin909** [comment]
@CrossR thanks for the tip, I've just had a quick try with the default font and the instructions you suggested but nothing (unusual) happens when I do that, although looks like the cracks youre getting in your screen shot are related to the width (which is normalised) as opposed to the height which I think means that based on font and maybe font size the normalization doesn't cover enough scenarios not that I know too much  about this bug though @bryphe explained what is likely causing it in #1203.

I personally was getting a very slight visual artefact, possibly a very minimal version of @badosu's screenshot but it was occurring under words so I thought the bug only related to the lack of normalisation for the height prop 😕 , although there's also the clipping which you have at the end of words on the screen shot which I also get which I'm desperate to fix which probably also relates to width normalisation not working in some cases

**Comment by badosu** [comment]
@Akin909 I am not able to reproduce this issue on the last stable version (0.2.19) anymore, I'll try checking if there's a way to reproduce them again.

**Comment by CrossR** [comment]
Since moving to the new release, this has come back for me unfortunately.

Steps for me to reproduce:
- Highlight any word with `*`
- Use `/ahksjdfjahsd` to clear the highlight (or `nohlsearch` which is less fun to type)

![image](https://user-images.githubusercontent.com/10038688/34690480-4406a2c4-f4b1-11e7-9c3e-00b9b0812b41.png)

This happens on most searches now, though not all.

**Comment by bryphe** [comment]
Ah bummer, just re-opened it.

Thanks for the heads up though, and for testing the latest release @CrossR ! 👍

**Comment by badosu** [comment]
I can't reproduce this issue anymore.

**Comment by CrossR** [comment]
Yep! This has been fixed in the experimental `webgl` renderer!

Cheers for closing.

**Comment by bryphe** [comment]
Awesome news! Thanks @Cryza 😄
