### ISSUE TITLE
Vue language server support

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#1119]
Investigate supporting `vue-language-server`.

- It looks like `.vue` files don't have a filetype set. We might need to bring in a plugin that can help us here, or add a minimal config to set a filetype for vue files.
- What's a good default configuration for `vue-language-server`? Does it need the `--stdio` flag?

**Comment by Akin909** [comment]
@bryphe with regards to language plugins, I imagine as we continue to have new languages added finding plugins for each will become laborious, in terminal vim I use [`polyglot`](https://github.com/sheerun/vim-polyglot) a vim plugin which uses vim's autoloading functionality to agglomerate language plugins for 50ish different languages. 

The plugin author uses autoloading so that vim's startup time is not affected instead it loads language plugins on demand per filetype. He essentially just bundles the most popular language plugins, it is well maintained and is constantly being upgraded meaning that going forward we would pick up any language plugins he provides. 

One down side worth noting is that for very extensive plugins that do much more than syntax highlight like `go.vim` which comes with a ton of different bits of functionality the plugin only takes the essentials like indenting, syntax highlighting etc. I think there are only a few exceptions like this were the most popular plugin tends to be doing many things and is too big to bundle with all of its functionality.

The repo specifies which plugins these are and in those cases it's best to install the plugin separately if you want that functionality.

**Comment by Akin909** [comment]
@bryphe I had a look at adding the `vue-language-server` it's a fairly large lsp so given the discussion re bundle size in #1190 (flow) it seems this is best added by the user.

It is essentially only a 2 step process `npm i -g vue-language-server` then adding `language.vue.serverCommands: vls`. 

Regarding the filetype detection it could be specified in the init.vim but a vim plugin is going to be needed for loads of functionality like indentation, highlighting etc. As above that could be vim polyglot or a single plugin aimed at vue etc. up to you, lemme know what you think.

 In the interim I can add the section re vue to the docs

**Comment by badosu** [comment]
@Akin909 Were you able to set the vue lsp integration manually?

**Comment by bryphe** [comment]
I'll close this out since we have documentation now - thanks @Akin909 ! 💯
