### ISSUE TITLE
experimental commandline takes 2 backspaces to go back 1 character.

### ISSUE THREAD

**Issue by Bretley** [onivim/oni#1183]
I have to type backspace twice as many times as I normally would... Not sure where the first one is going but it isn't making it to the input for the commandline

**Comment by bryphe** [comment]
Ah ya, actually I noticed this too - it also takes two 'enters' for me to execute the command. Perhaps it's related?

**Comment by Bretley** [comment]
Most likely, you also have to double tap escape to get back out. Also tabs aren't working for me, it just selects it like it would in a website..

 I'm going to take a wild guess and say that the HTMLInput has something to do with this. my version was just feeding the keys to neovim and rendering the output but clearly one of the changes is 'eating' the extra keys.

**Comment by Akin909** [comment]
Yep this is entirely due to the input, spent a bit of time trying to figure out how to create a cursor there and was trying to use a native one the problem though is that there isn't a change event going on. Not sure what the final solution should be but @bryphe  you mentioned reusing the `cursor.tsx` that way theres an output element with mock a cursor, there are also some actions in place for getting the cursor position, though not sure theyre hooked up. Could potentially return this to being a div in the mean time as its an improvement though for me not being able to see where you are renders the `cmdline` unusable 🙇

**Comment by Akin909** [comment]
should be fixed by #1191 I've added a cursor and removed the excessive focus forcing so double input bug doesn't occur, also no longer using an input element

**Comment by bryphe** [comment]
Cool, looks like with the latest master this doesn't repro for me (and it's working great in general). Thanks for the fix, @Akin909 ! I'll close this out.
