### ISSUE TITLE
Auto-completion masses up the dot command

### ISSUE THREAD

**Issue by TalAmuyal** [onivim/oni#1201]
Auto-completion isn't recorded as part of the input.

Input: `i clas\n<esc>0.`.
Expected output: ` class class`
Actual output: ` clas class`

**Comment by bryphe** [comment]
Thanks @TalAmuyal for finding this! Somewhat similiar to #1200 - since we are using the `nvim_buf_set_lines` API call, it's not repeatable via the `.`. 

The `.` command is a bit easier to solve I believe - [vim-repeat](https://github.com/tpope/vim-repeat) solves this for a similiar case of making plugin calls repeatable.

A quick-and-dirty way to make this work would be to execute a command something like `:execute "normal! acompletion\<esc>u"` after the completion is set - but not sure if there would be other issues there.

**Comment by TalAmuyal** [comment]
You are right, merging with #1200.
