### ISSUE TITLE
Build windows version of Neovim as part of Oni

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#123]
Right now, we use a prebuilt Neovim binary, but have no pipeline to build Neovim from source for Windows. It'd be helpful to hook that up as part of the build chain, so that we could add the `gui_oni` feature.

**Comment by CrossR** [comment]
Since #875 was merged in, this (and #326) can be closed I think, and we can make a separate more focused ticket on the final part of this which is to add a `gui_oni` feature. 

From the comments on #119 and browsing the VimR neovim fork, the only real thing to add is a single ifdef to `eval.c` and pass a flag for that to cmake, and then the feature should be baked in.

I've tested this on my fork of neovim and it does indeed bake in the `gui_oni` feature, allowing my `init.vim` to swap to using `if has ('gui_oni')` instead of `if exists('g:gui_oni')` as it is currently.

So we could get a fork of neovim into the org with the feature added, which is easy enough. Creating the binaries may be a little more tricky, but thats just because I've not had to make the binaries for Windows / Mac before, which I assume someone else has! Then as far as I understand it, if the binaries are in the same form, we can just point the `oni-neovim-binaries` script at the new release in our fork. 

From there we can start to look into the more interesting bits, I see that VimR also has a few tiny changes to neovim (https://github.com/neovim/neovim/compare/master...qvacua:master), or I know that a web-assembly build was mentioned too.

**Comment by bryphe** [comment]
Thanks for the feedback & investigation here, @CrossR ! 

> Since #875 was merged in, this (and #326) can be closed I think, and we can make a separate more focused ticket on the final part of this which is to add a gui_oni feature.

Sounds good - perhaps it even makes sense to make a ticket on the `oni-neovim-binaries` repo? It sounds like you've figured out where we'd need to add it.

> So we could get a fork of neovim into the org with the feature added, which is easy enough. Creating the binaries may be a little more tricky, but thats just because I've not had to make the binaries for Windows / Mac before, which I assume someone else has! 

Same here, I haven't actually tried to build on Windows 😄 Much less set up appveyor for it.

I haven't heard too many people asking for this recently (perhaps the `g:gui_oni` is sufficient), so it might make sense to hold off for now. Especially since you added the capability to load a custom `init.vim` for Oni, which helps here too.

We can bring it back as an issue on the `oni-neovim-binaries` repo though if it is something that would be useful. I'll close this one for now, and we can open a new issue to track the `gui_oni` feature if necessary.
