### ISSUE TITLE
set sm! causes tab to loose focus.

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#1264]
Vim's showmatch feature causes the current "tab" to loose focus while the matching paren is being highlighted.

**Comment by bryphe** [comment]
Interesting! First time learning about the `:showmatch` command... it's amazing how much there is to learn about Vim 😄 

I'm able to reproduce this by setting `tabs.mode` to `tabs` and setting `autoClosingPairs.enabled` to `false`.

The 'highlight' we show for focus on the tab is a function of the current mode. It turns out, that while the `showmatch` highlight is active, our mode actually gets set to `showmatch` from Neovim (which we don't handle):
![image](https://user-images.githubusercontent.com/13532591/34803156-98795f42-f626-11e7-948b-9f0c361ecd56.png)

When I test this in gvim, or terminal vim on mac, it appears that Vim just stays in insert mode. A safe fix for this would be to treat the `showmatch` mode we're getting from Neovim as `insert`, at least as far as Oni's UI integrations are concerned.
