### ISSUE TITLE
QuickOpen does not prioritize matches accordingly

### ISSUE THREAD

**Issue by badosu** [onivim/oni#1266]
In this example I have:

- `src/store/index.js`
- `src/router/index.js`

If I type `storeindex` this is what I get:

![screenshot from 2018-01-10 10-46-14](https://user-images.githubusercontent.com/347552/34773619-7f8b3452-f5f3-11e7-8698-d68800fbac43.png)

I would expect index on store to be more important than a file that does not have store in the path.

**Comment by CrossR** [comment]
Have you tried with `"editor.quickOpen.filterStrategy"` set to `"regex"`? It would fix that specific issue, since `storeindex` would only match on the second one.

Though it may be too strong for what you want generally, such that we might just want an optional sort applying to the standard `"fuse"` as well if possible.

**Comment by badosu** [comment]
@CrossR Does the `regex` strategy work as a reliable fuzzy-finder strategy?

**Comment by CrossR** [comment]
I've found it quite nice, I'm fairly used to just typing a bit of the name of the folder I want, and then the file I want. If I'm less sure and just type the name of the file, it seems to work well still.

**Comment by badosu** [comment]
Seems like it's working out, I wonder why this is not the default strategy.

**Comment by bryphe** [comment]
Awesome! I was hoping the `regex` strategy would be more intuitive / address some of the issues you had, @badosu 

> Seems like it's working out, I wonder why this is not the default strategy.

I was actually considering switching this to be the default (i'm using it as well). If both you and @CrossR are using it and it's working out, might be worth swapping the default for next release (and seeing if anyone misses the old behavior 😄 )

**Comment by hoschi** [comment]
Hm with `regex` strategy the dir delimiter `/` doesn't work. Probably not escaped?

E.g. when opening general files which exist in more than one dir like `src/features/tasks/index.stories.js` I can't type `tasks/in` anymore. 

Also with regex some matches are very weird. Why does it highlight `xxxRCxxxEAT...` when my search starts with `act`?
![2018-01-11-152559_416x149_scrot](https://user-images.githubusercontent.com/163128/34830348-e27f8cd4-f6e3-11e7-87ef-c4c551edd986.png)

**Comment by bryphe** [comment]
> Hm with regex strategy the dir delimiter / doesn't work. Probably not escaped?

Good catch, ya, I think it isn't escaped. We should fix this.

> Also with regex some matches are very weird. Why does it highlight xxxRCxxxEAT... when my search starts with act?

I think this is a bug with the highlighter - it is just highlighting characters in the string as they show up, regardless of the order. Should be fixed too

**Comment by badosu** [comment]
> I think this is a bug with the highlighter - it is just highlighting characters in the string as they show up, regardless of the order. Should be fixed too

I noticed this behaviour on the previous strategy too, so maybe not particular to the regex one.

@bryphe I think using regex as the default strategy is sensible, it works as I expected having used many other similar tools in the past. If not used as default at least we should talk about this configuration with more emphasys on the wiki.

Then I think we can close this issue.

**Comment by hoschi** [comment]
I tried current default strategy and regex since Monday, because of another bug which forces me to use Oni instead of CtrlP and I have to say the matches are not near the quality of what I'm used to from CtrlP or FZF (terminal).

**Comment by hoschi** [comment]
Some examples:

top left: FZF
top right: CtrlP
bottom: Oni (default strategy)
![2018-01-12-120159_2051x1404_scrot](https://user-images.githubusercontent.com/163128/34872214-66deb584-f790-11e7-80a2-f84c57a9f0f1.png)

Oni regex:
![2018-01-12-120404_2044x701_scrot](https://user-images.githubusercontent.com/163128/34872303-bd86804c-f790-11e7-9d76-35a9f7b3cb46.png)

FZF,CtrlP,Oni (default)
![2018-01-12-120825_2054x1404_scrot](https://user-images.githubusercontent.com/163128/34872495-4cb7571e-f791-11e7-866f-208efb89ca1d.png)
regex:
![2018-01-12-120718_2044x701_scrot](https://user-images.githubusercontent.com/163128/34872445-2429f996-f791-11e7-8e08-9554ed21868c.png)

FZF,CtrlP,Oni (default)
![2018-01-12-121228_2055x1408_scrot](https://user-images.githubusercontent.com/163128/34872609-df2eb286-f791-11e7-8406-13ee5af20457.png)
regex:
![2018-01-12-121325_2044x701_scrot](https://user-images.githubusercontent.com/163128/34872640-ff634792-f791-11e7-9fa5-cb615244768c.png)

You can test it on your own here, I checked in the `jsconfig.json` files https://github.com/hoschi/yode/tree/develop/

**Comment by CrossR** [comment]
Just out of curiosity, I tried @hoschi tests in VS Code as well, since we are using the ripgrep binary they use as far as I know. The searches all return the same results as FZF in his tests, or at least a lot closer. Only exception is the final one, where it is the same as CtrlP, since FZF is including node_modules which VSCode seems to ignore.

![image](https://user-images.githubusercontent.com/10038688/34875004-5e4dfe68-f793-11e7-97d4-41e5fc75b684.png)
![image](https://user-images.githubusercontent.com/10038688/34875022-83ed928c-f793-11e7-9c90-8dc8730e2ad6.png)
![image](https://user-images.githubusercontent.com/10038688/34875095-c16b7566-f793-11e7-8c3e-0f3aaee6e0e3.png)

**Comment by badosu** [comment]
@hoschi I agree that the regex is still non-optimal, perhaps we could add an issue to make QuickOpen a more reliable fuzzy-finder.

But compared to before using the regex strategy the difference is abismal, it was pretty much unusable for me before.

So I think we should use this issue to track changing the default to regex or make emphasis for it on the README and track the improvement of the strategy on another issue, with more detailed accounts on what is the expected behaviour (as you've done on the previous comments).

**Comment by CrossR** [comment]
I've had a look into this in other editors, and I think there is a few things we can potentially do, put I'm not fully sure of their cost.

By the looks of VSCode they use a big scoring algorithm to apply scores to the results, then that is used for the sorting : https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/common/quickOpenScorer.ts
Looks to basically just give higher scores depending on if certain criteria are met.

We could potentially do something like that, but it could also just slow down the search or cause more issues when we have to add edge cases after edge case. Though, there were still some issues complaining it wasn't as good as FZF still.

That said, it would improve the search further, since currently I don't think we do anything like this.

**Comment by badosu** [comment]
I've been using the regex strategy and it has worked well so far, so I think we can close this issue by me.

We can track improvements to the refinement process on https://github.com/onivim/oni/issues/1632, there it specifically targets multiple search items but we can discuss the refinement process there.

Let me know if you think there are pending points to be addressed in this issue.
