### ISSUE TITLE
Markdown Preview Dim Persists

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1277]
@TalAmuyal Fantastic work on the markdown preview 🎉 

I've been using it a fair bit vs less elegant terminal vim plugins.
Whilst using it I noticed that after it opens it sets a `not-focused` class on the editor element which isnt removed by closing the plugin (by which I mean toggling it, not sure if that kills the process). I've found that by removing that class from the editor component the dimming goes away.

**Comment by bryphe** [comment]
> @TalAmuyal Fantastic work on the markdown preview 🎉

💯 

> I've been using it a fair bit vs less elegant terminal vim plugins.

Same here, it's been working great! Getting ready to tweet about it.

> Whilst using it I noticed that after it opens it sets a not-focused class on the editor element which isnt removed by closing the plugin (by which I mean toggling it, not sure if that kills the process). I've found that by removing that class from the editor component the dimming goes away.

Nice catch! I think this might be my fault. In the WindowManager, we run `_focusNewSplit` when we create a new split, but there isn't really a way to bring the focus back at the moment. A quick fix would be to add a `focusSplit` method, and then in the markdown preview code, we'd call that immediately after creating the split (we'd call focus on the current `activeEditor`, so that it sticks there).
