### ISSUE TITLE
ALT/META key seems to be ignored

### ISSUE THREAD

**Issue by justinmk** [onivim/oni#1331]
Steps to reproduce:

    :nnoremap <M-a> :echo "foo"<CR>

Pressing ALT-a does not invoke the `<M-a>` mapping.

**Comment by bryphe** [comment]
Thanks for the issue, @justinmk ! Really appreciate you trying the build out.

I just tested this scenario on OSX and Windows:
- __Windows__  - it seems that it gets resolved and sent to Neovim as `<a-a>`. The `<m-a>` mapping seems to pick this up anyway.
- __OSX__ - on my keyboard layout (US), it gets resolved to ``. So I have to change the binding to `:nnoremap :echo "foo"<CR>` to get it to work.

Which platform are you on? And which keyboard layout did you test with? I'll see if I can reproduce it too.

Sometimes there is some flakiness with the `Alt` key in different keyboard layouts, because of how we try and differentiate the `AltGr` cases (like #696 ).

**Comment by justinmk** [comment]
I'm on macos. Getting around the default macos handling requires some fiddling, but I would expect electron to have a built-in mechanism to handle it as a modifier.

**Comment by bryphe** [comment]
Hmm, I tried with binary `nvim` on OSX, and I see the same behavior - I need to use `:nnoremap å :echo "foo"<CR> ` in terminal nvim for this binding to work correctly. So it makes sense for Oni to behave the same way here, IMO - but I could be missing something. Is the `<m-a>` binding expected to work in terminal `nvim` for this case?

> Getting around the default macos handling requires some fiddling, but I would expect electron to have a built-in mechanism to handle it as a modifier.

Yes, I assumed so too! Unfortunately, it's not great for some of this input scenarios. An example is pressing `<A-S-a>` - we get this character. However, it comes to us as an event like:
```
{ key: '', shiftKey: true, altKey: true }
```

So if we naively convert this to input `nvim` expects, we'd send: `<A-S- >` - which isn't correct.

We end up using Atom's [keyboard-layout](https://github.com/atom/keyboard-layout) module to ask how the character gets generated, in order to figure out which keys to 'ignore' when sending to Neovim. In the above case, we'd figure out that the ` ` key is produced by alt+shift+a, so we should ignore the alt+shift when sending to Neovim. Definitely more complicated than it _should_ be.... but luckily that module is available to help us out here.

**Comment by justinmk** [comment]
> Hmm, I tried with binary nvim on OSX, and I see the same behavior

Terminal.app and iTerm2 have an option to "send option as ESC", and the standard advice is to enable this option. Otherwise yes, you get the default OS-wide behavior that you are seeing. 

Low-level applications like [kitty](https://github.com/kovidgoyal/kitty/issues/123) must implement their own mechanisms to work around this macOS behavior. But electron/Chromium should have already dealt with this.

**Comment by justinmk** [comment]
Yes. I guess I'm biased because I use vim across platforms and don't want platform-specific quirks in my config.

> Another option that would need an API extension would be for us to send both candidates and let Neovim decide what to use

This could probably be supported with a new keycode form, something like:

    nvim_input('<? å a-8 >')

**Comment by bryphe** [comment]
> Yes. I guess I'm biased because I use vim across platforms and don't want platform-specific quirks in my config.

Agree 100% 👍Having to create platform-specific config is a terrible experience.
 
> This could probably be supported with a new keycode form, something like: `    nvim_input('<? å a-8 >')`

This would be excellent. It would mean minimal overhead for Oni - we could just send you both candidates and Neovim would do the right thing for us. I believe this would be applicable for the other browser clients hosting Neovim as well (would be interesting to see if @Chillee has run into this w/ VSCodeNeovim)

**Comment by bryphe** [comment]
Per our discussion on Gitter - seems like we can implement this resolution via a custom VimL/Lua function, which would be simpler than updating the `nvim_input` API. If it turns out this is a requirement for other external UIs too, we can look at generalizing it/factoring it out.

**Comment by bfredl** [comment]
@bryphe do you mean the external UI will call a VimL/lua function instead of the `nvim_input`? Then note that the function call will not be executed immediately in many contexts where nvim is waiting for user input, which can lead to unexpected behavior (such as user input being reordered).

**Comment by bryphe** [comment]
> @bryphe do you mean the external UI will call a VimL/lua function instead of the nvim_input?

Right, that's what I was thinking. Otherwise, we'd need the logic either on the `nvim` side (potentially with the alternate keycode form), or on the Oni client side (requiring synchronizing of the keyamps).

>  Then note that the function call will not be executed immediately in many contexts where nvim is waiting for user input, which can lead to unexpected behavior (such as user input being reordered).

Ah, good catch... I forgot about this. This would be problematic.

**Comment by justinmk** [comment]
That may not be a big problem. Check `nvim_get_mode().blocking`. If it's blocking, it doesn't really matter what you send because mappings usually don't apply during Press-Enter prompt. If it's not blocking, it's ok to proceed as described above.

**Comment by bronzehedwick** [comment]
Any movement on this issue? I just tried out Oni and am very impressed, but none of my meta bindings work 😞

**Comment by bryphe** [comment]
@bronzehedwick - unfortunately nothing new here, would ❤️ help if anyone is up for investigating it.

**Comment by bronzehedwick** [comment]
Okay gotcha. I have never coded anything like an editor before, but I'd like to contribute to the project. I think I'll try one of the good first issues first and get more comfortable before trying this.

**Comment by bryphe** [comment]
> Okay gotcha. I have never coded anything like an editor before, but I'd like to contribute to the project

Awesome, we can definitely use help! 💯 

> I think I'll try one of the good first issues first and get more comfortable before trying this.

Sounds good. Let me know if you have any questions!

**Comment by VincentZhou98** [comment]
So miss the meta key. if something like `set macmeta`  command on `macvim` can work, that will be great.

**Comment by EarthCitizen** [comment]
I don't know what VimR does under the hood, but it gives the option "Use Left Option as Meta" and "Use Right Option as Meta". If someone were to look into that, it could probably be migrated to Electron.

**Comment by haifengkao** [comment]
here is how NyaoVim handles the meta key on OSX
https://github.com/rhysd/neovim-component/commit/5b356d88669e8267cb27d128cd33f062ec5d8e0f

**Comment by garetmckinley** [comment]
Why was this issue closed? AFAICT this is still very much a problem with Oni. I love the editor, but it's really frustrating having no access to my meta bindings. I've basically run out of modifiers to bind and I have a whole bunch of functions that are just unbound on macOS only. I would go the route of rebinding my caps lock to a meta key, but I'm using caps lock for esc.

I understand wanting to keep the experience consistent with other editors, but considering that Oni is clearly a (neo)vim powered editor, I think it's more important to keep it consistent with the vim experience. If I open the exact same neovim configuration in terminal side by side with Oni, they behave differently.
