### ISSUE TITLE
Welcome Menu - Input and loading

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1413]
I've again bundled two bugs together as they both pertain to to the welcome menu.
The first of which is that the welcome screen now swallows input aimed for vim relates to #1398 which means that on opening vim one of my first actions which is to open the `commandline` and open a file or a session is now blocked.

Secondly the welcome screen ~~only appears if I have oni open at full screen if oni starts at half screen for some inscrutable reason the welcome menu does not appear instead I get an empty buffer titled welcome~~ only appears with my `init.vim` disabled going to try commenting out sections to find the cause, although I think if a user's init.vim might somehow break the welcome menu due to maybe a competing `BufEnter` command etc there might need to be logic to give the menu priority

EDIT: Apologies, I appreciate this issue is ambiguous, what I'm trying to convey is that with the welcome menu enabled my keyboard input seems to disappear in a confusing manner hitting certain keys does nothing 😕, and regarding its appearance it's likely an interaction with another plugin but potential plugin interaction is the concern as has happened in my case

**Comment by Akin909** [comment]
Looked into both of these and it seems the issue with when welcome screen appears relates to my `vimrc` as not loading it seems to allow the screen to appear as expected. I noticed that vim actually seems to be creating a real buffer for the welcome screen.

I dont know much about how the buffer layer works but I was thinking if it makes actual vim buffers it might be good to have them be `scratch` buffer and setting them to `nofile` as I've noticed thats its possible to actually run the save command and create a file in the current workspace called `WELCOME`

As to the specific cause of the error that will take a bit more digging as my config is enormous

**Comment by bryphe** [comment]
Thanks for testing out the welcome screen @Akin909 - really appreciate it and it will help us iron out all the issues before the next release 💯 

> which means that on opening vim one of my first actions which is to open the commandline and open a file or a session is now blocked.

This is definitely a blocker to turning on the feature. The welcome screen even advertises that this should be available 😄 

> I dont know much about how the buffer layer works but I was thinking if it makes actual vim buffers it might be good to have them be scratch buffer and setting them to nofile as I've noticed thats its possible to actually run the save command and create a file in the current workspace called WELCOME

Buffer layers aren't too complex - there essentially just a React component that renders on top of the buffer. They get a little extra context to figure out how to map buffer coordinates (the `context` passed to the render function), but otherwise it's just a plain react component! I'm envisioning some cool stuff we can do later with this - like for image files, we display the actual image instead of buffer text. And it will serve as the foundation for the interactive vim tutor stuff later.

But yes, we basically create an empty `WELCOME` buffer to host that layer. Setting it to `scratch` and `nofile` is a great idea - we wouldn't want to write or save this.

The welcome layer has one level of extra complexity - it is just a React component, but it also has the `<VimNavigator />` component to manage the input. That actually uses a shared Neovim instance under the hood to handle keyboard nav. It's actually the same `SharedNeovimInstance` that the file explorer and sidebar use too (they all use the `<VimNavigator />` component). I'm thinking that, for that second neovim instance, perhaps it doesn't make sense to load the users `init.vim`, in order to minimize conflicts?
