### ISSUE TITLE
Rename confirm with enter not registering

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1426]
@bryphe following #1417 where I believe you consolidated some functionality the `rename` commit action on hitting enter no longer works i.e. you it opens as expected and still closes with `<esc>` but does not register hitting `<enter>`

**Comment by bryphe** [comment]
Thanks for catching this, @Akin909 ! Really appreciate all your help with stabilizing changes. 

Ah es, I meant to wire up the `<enter>` key to this too (wanted the text inputs in the sidebar to have an `onComplete` event, and it made sense to have shared functionality instead of implementing new commands/keybindings for this all the time).
