### ISSUE TITLE
Possibility of switching to ramda from lodash

### ISSUE THREAD

**Issue by Rafi993** [onivim/oni#145]
Is there any plans to switch to [ramda](http://ramdajs.com/0.20.1/index.html) from lodash.Since ramda seems to promote more functional approach and is very minimal compared to lodash (I know this a very opionated topic and please forgive me those who are offended by this question )

**Comment by extr0py** [comment]
I'm open to it! I actually don't know that much about ramda. I used lodash just because I was familiar with that from my day job, so it was my default choice :)

I see a few discussions here:
https://www.reddit.com/r/javascript/comments/3537kx/underscore_lodash_ramda/
http://funkyjavascript.com/i-think-ramda-might-be-better-than-lodash-or-underscore/

It seems like lodash still has a lot more volume in terms of npm downloads today. It'd be interesting to see what the impact of it would be (for example, if there places where lodash is being used today in Oni that could be improved with ramda). I know there are a few places where the chaining is awkward with the lodash functions

**Comment by Rafi993** [comment]
@extr0py  It is true that lodash has more users but ramda is relatively new compared to lodash or underscore. Using ramda will make the code more readable and if the UI is made more modular enough we can make  the moving parts of the editor as just compossable functions. Making it easy to maintain and more customizable.

**Comment by hoschi** [comment]
I use Ramda for years now and `R.pipe` combined with other Ramda functions and ES6 arrow functions can replace a good amount of imperative code and are *much* more readable:
http://randycoulman.com/blog/2016/06/14/thinking-in-ramda-declarative-programming/

**Comment by bryphe** [comment]
I'll close this out for now, since it's been open for almost a year. I'm open to a PR to convert from lodash to ramda, but I don't think it's necessary to track in this issue. We've started to using `RxJS` as well, and our `lodash` surface area is much smaller.
