### ISSUE TITLE
Reveal active buffer in file explorer

### ISSUE THREAD

**Issue by tobiasandersen** [onivim/oni#1567]
There's a command in Atom called `tree-view:reveal-active-file` that I think would be really cool to have in Oni as well. When invoked in Oni, I'd expect it to look at the currently active buffer and locate that buffer's file in the file explorer (sidebar) and give focus to it.

I'm not familiar with the codebase, so it's a bit hard to tell how hard this would be to implement. But I'd love to give it a shot if you agree it's a feature worth adding.

**Comment by someguynamedmatt** [comment]
@tobiasandersen Awesome idea! These directories might be a good place to start are:

**Comment by Akin909** [comment]
@tobiasandersen I  think this would be really cool functionality sort off like `NERDTree's` focus file and the atom reveal you mention. In terms of how and where to look to implement this I'd initially point you towards [this file](https://github.com/onivim/oni/blob/44e162d359c6b2a669e5d6dbcef4589c4de90b56/browser/src/Services/Explorer/ExplorerSplit.tsx#L71) which is where the logic for the Explorer lives. 

Oni has an api for registering commands the link should give you an example. Haven't quite thought it all through but you could potentially create a function which takes in the current active buffer's file path (the `editorManager` has access via `editorManager.activeEditor.activeBuffer.filePath` and then pass it to the explorer in which is in the same dir called `ExplorerView` and have it focus the matching node. Might need to have a look around to figure exactly where to go from there but hopefully that gives you some idea.

 Thanks so much for looking at this ^^ 👍 lemme know if you need any help or info.

**Comment by bryphe** [comment]
👍 , this would be awesome!

**Comment by tobiasandersen** [comment]
Thanks guys, I'll look into it this week!

**Comment by feltech** [comment]
I think this can be closed now, due to https://github.com/onivim/oni/commit/b6bdb4bd68a41b4c751da02e74ddfb3512ebe758

**Comment by CrossR** [comment]
Yep!

Thanks for the contribution @feltech, certainly something I've wished Oni had before!

It may be worth you and @Akin909 co-ordinating at some point to get this (and the other explorer features) into the Wiki. There is loads of cool functionality being added to it, but I think the documentation around the explorer currently is pretty barebones.

There is shortcuts over at https://github.com/onivim/oni/wiki/Shortcuts, but they should probably be linked from the https://github.com/onivim/oni/wiki/Configuration page, plus add maybe a new section to highlight some of these useful features that people might want to bind in some way etc.

**Comment by Akin909** [comment]
@CrossR yeah definitely a bit behind on documentation re new functionality will have a look this weekend at adding an explorer section to explain the different bits of functionality 👍

**Comment by feltech** [comment]
A couple of rough one-liners to extract commands as a markdown table...

For commands registered via `new CallbackCommand` or `new Command`
```
 $ ag -A5 -w registerCommand | grep -EA3 "new (Callback)?Command" | grep -Ev "new (Callback)?Command" | awk 'BEGIN{command=""; name=""; detail=""; print "|command|name|detail|\n|---|---|---|"} /^--/{print "| "command" | "name" | "detail"| "; command="";name="";detail=""} /".+"/{$0=gensub(".*\"(.+)\".*", "\\1", "g"); if (!command) {command=$0} else if (!name) { name=$0 } else if (!detail) { detail=$0 }; next } {if (!name) { name=" " } else if (!detail) { detail=" " }} END{print "| "command" | "name" | "detail" |"}'
```
and for commands registered directly
```
$ ag -A5 -w registerCommand | grep -EA3 "new (Callback)?Command" | grep -Ev "new (Callback)?Command" | awk 'BEGIN{command=""; name=""; detail=""; print "|command|name|detail|\n|---|---|---|"} /^--/{print "| "command" | "name" | "detail"| "; command="";name="";detail=""; next} /".+"/{$0=gensub(".*\"(.+)\".*", "\\1", "g"); if (!command) {command=$0} else if (!name) { name=$0 } else if (!detail) { detail=$0 }; next } {if (!name) { name=" " } else if (!detail) { detail=" " }} END{print "| "command" | "name" | "detail" |"}'
```
Giving

|command|name|detail|
|---|---|---|
| explorer.toggle | Explorer: Toggle Visibility | Toggles the explorer in the sidebar| 
| explorer.locate.buffer |   | Explorer: Locate Current Buffer| 
| explorer.delete.persist |   |  | 
| explorer.delete |   |  | 
| explorer.yank |   | Explorer: Yank Selected Item| 
| explorer.undo |   | Explorer: Undo Last Action| 
| explorer.paste |   | Explorer: Move/Paste Selected Item| 
| explorer.refresh |   | Explorer: Refresh The Tree| 
| explorer.create.file |   | Explorer: Create A New File| 
| explorer.create.folder |   | Explorer: Create A New Directory| 
| explorer.expand.directory |   | Explorer: Expand Selected Directory| 
| explorer.collapse.directory |   | Explorer: Collapse Selected Directory| 
| explorer.rename |   | Explorer: Rename Selected File/Folder| 
| preview.open |   | Preview: Open in Vertical Split| 
| sneak.show |   | Sneak: Current Window| 
| sneak.hide |   | Sneak: Hide| 
| oni.themes.choose |   | Themes: Choose Theme| 
| select |   |  | 
| markdown.openPreview |   | Open Markdown Preview| 
| markdown.closePreview |   | Close Markdown Preview| 
| markdown.togglePreview |   | Toggle Markdown Preview |

and

|command|name|detail|
|---|---|---|
| explorer.toggle | Explorer: Toggle Visibility | Toggles the explorer in the sidebar| 
| explorer.locate.buffer | Explorer: Locate Current Buffer | Locate current buffer in file tree| 
| explorer.delete.persist |   |  | 
| explorer.delete |   |  | 
| explorer.yank | Explorer: Yank Selected Item | Select a file to move| 
| explorer.undo | Explorer: Undo Last Action |  | 
| explorer.paste | Explorer: Move/Paste Selected Item | Paste the last yanked item| 
| explorer.refresh | Explorer: Refresh The Tree | Updates the explorer with the latest state on the file system| 
| explorer.create.file | Explorer: Create A New File |  | 
| explorer.create.folder | Explorer: Create A New Directory |  | 
| explorer.expand.directory | Explorer: Expand Selected Directory |  | 
| explorer.collapse.directory | Explorer: Collapse Selected Directory |  | 
| explorer.rename | Explorer: Rename Selected File/Folder |  | 
| preview.open | Preview: Open in Vertical Split | Open preview pane in a vertical split| 
| sneak.show | Sneak: Current Window | Show commands for current window| 
| sneak.hide | Sneak: Hide | Hide sneak view| 
| oni.themes.choose | Themes: Choose Theme | Choose your theme from the available bundled themes.| 
| select |   |  | 
| markdown.openPreview | Open Markdown Preview | Open the Markdown preview pane if it is not already opened| 
| markdown.closePreview | Close Markdown Preview | Close the Markdown preview pane if it is not already closed| 
| markdown.togglePreview | Toggle Markdown Preview | Open the Markdown preview pane if it is closed, otherwise open it |

**Comment by feltech** [comment]
^ just a bit of lunch time fun that may be helpful for the wiki ;)

**Comment by ELLIOTTCABLE** [comment]
Is there any way to trigger this *automatically*, on every file opened? I generally use Denite, instead of Oni's built-in fuzzy-finder, to navigate files — or just plain `:e` — and I'd love to keep the File Explorer open, as a general ‘visual overview’ of my project, but …
