### ISSUE TITLE
Cannot delete a word with Alt+Del or a line with Cmd+Del

### ISSUE THREAD

**Issue by rgehan** [onivim/oni#1743]
I think it should be possible to use:
- `Alt+Del` to delete a word backward in insert mode, the command palette and the Vim command line
- `Cmd+Del` to delete a full line

I tried using `Cmd+A` to delete the whole input, but it simply prints an `a`.

**Oni**: v0.3.0
**OS**: Mac OS High Sierra 10.13.3

**Comment by CrossR** [comment]
We do have that functionality, but using vim-style keybinds, which are:
- `Ctrl-h` - Delete a single char.
- `Ctrl-w` - Delete a word.
- `Ctrl-u` - Delete a line.

That said, I think they are hard-coded right now, so maybe it worth the making of an issue to:
* Move the simple text inputs (QuickOpen etc) to use the VimNavigator keybinds. (ie currently we are just faking it and adding vim-style keybinds, where we should be using the VimNavigator which is backed by neovim, like the explorer and more have).
* Add some form of keybinds/settings option for them, since a few people have wanted specific actions inside VimNavigator and its not currently possible (that  I know of).

**Comment by rgehan** [comment]
@CrossR It seems like these three keybindings already work in the Command Palette, the Quick Open and the ":command" input; they'd need to be configurable though

**Comment by rgehan** [comment]
@CrossR I just looked at `VimNavigator` and it seems like it is used for (obviously) navigating lists and grid (soon); but I don't really understand how this could be used for a text input

**Comment by CrossR** [comment]
From my understanding, `VimNavigator` is actually powered by an instance of NeoVim, such that we should be able to do an awful lot with it!

That said, it also isn't used for the sort of stuff I've suggested yet, so the bits I'm suggesting will probably end up being a decent amount of work, since we'd need to start mirroring contents across them. That would then mean we'd have a coherent style of input across everything using it, rather than currently with certain parts having "fake" vim-style keybind, and allow for a lot of cool things in the future.

It may instead be worth (for now) creating a config option for the hard coded options, and create a second more targeted (or look at the existing tickets relating to the extensions for `VimNavigator`) issue for the broader changes. Any opinions @bryphe ?

**Comment by bryphe** [comment]
> From my understanding, VimNavigator is actually powered by an instance of NeoVim, such that we should be able to do an awful lot with it!

Definitely! Under the hood, there's a shared instance of Neovim as you mentioned:
https://github.com/onivim/oni/blob/6d9cd90e1c20bc2c4ae3ce087f8695d5856457b0/browser/src/neovim/SharedNeovimInstance.ts#L152

Right now, it only has the `bindToMenu` which is pretty specific to a menu - the underlying `MenuBinding` maps an array of items -> buffer text, and then vice versa, from a cursor position -> an item. I was hoping to have another type of binding, like `bindToInput` or `bindToTextArea` - that would just create a new buffer, take in `input` events, and then have an event whenever the buffer changes. 

We'd probably need another component backing this as opposed to `<VimNavigator />` though - like `<VimTextBox />` or something, but it would still use that `SharedNeovimInstance` under the hood. We'd probably want some more text-focused-props, like `onTextChanged` or something. This would be great for our text in menus.... and potentially as a way to input text in browser scenarios, too!

IMO I think this would be the ideal approach for it... Then you could have your insert mode bindings behave the same way in the command palette/quick open.

**Comment by badosu** [comment]
I am not sure if we would want to support an additional edit keybinding foreign to vim, it could give unexpected results.

This can done remapping in `init.vim`.
