### ISSUE TITLE
`:wq` and `:q` close the whole app instead of just a tab

### ISSUE THREAD

**Issue by rgehan** [onivim/oni#1745]
It seems a bit counter-intuitive to have `:q` or `:wq` close the whole editor instead of just the currently edited tab.

In Neovim, when you have multiple windows on display, `:q` only closes the focused one.

**Oni**: v0.3.0
**OS**: Mac OS High Sierra 10.13.3

**Comment by CrossR** [comment]
Do you know what `tabs.mode` option you are using? If you haven't changed it, we default to using `buffers` in all versions up to v.0.3.0.

This means an Oni tab is actually a Neovim buffer. So using `:q` of any form will close the whole editor, unless you have opened some Neovim tabs with `:tabnew` etc. This is how it works in neovim as far as I know, if you open up multiple files without using neovim tabs.

In the next release we are swapping to using `tabs.mode` as `tabs` by default, ie an Oni tab is actually a Neovim tab.

When this is the case, closing a tab with `:q` or `:wq`, only the current tab is closed.

There may be a separate issue about getting `buffers` to work like this, but that would be up to @bryphe, since technically we are just mirroring Neovim as far as I know.

**Comment by CrossR** [comment]
Shout up if the wording is confusing, it does get a bit confusing to talk about, but at least in the next release what Oni and what neovim consider a tab is the same!

**Comment by badosu** [comment]
@rgehan Did you figure out the error? If not feel free to reopen the issue as it's a pretty serious one.

**Comment by rgehan** [comment]
If I'm not mistaken, it looks like it is *intended* behavior (at least *accepted*) until `tabs.mode` is changed from `buffers` to `tabs`.
