### ISSUE TITLE
Quick Open should be case insensitive

### ISSUE THREAD

**Issue by rgehan** [onivim/oni#1813]
It would be more intuitive to be able to look for a file (even capitalized) by searching for a lowercase string

**Comment by CrossR** [comment]
What behaviour are you currently seeing?

The default for the quick open is to use `"smart"` case sensitivity, which is if an all lower case string is given, then we do a case insensitive search. Otherwise, if any capitalised letters are given, the search swaps to case sensitive.

There is a config option (`"menu.caseSensitive"`) to change that to simply always be case sensitive or never be case sensitive (set it to `true` or `false`).

If my description didn't make sense there, the code for it can be found here : https://github.com/onivim/oni/blob/262098fefd7e82bb69b0b9b68ff66ba6af3d18d8/browser/src/Services/Menu/MenuFilter.ts#L16

**Comment by badosu** [comment]
@rgehan As @CrossR has already said, unless you type a capitalized character the search should be case insensitive.

I think this is a pretty good default, let us know if you think of a better behaviour.

**Comment by rgehan** [comment]
I'm coming from VSCode so that was a bit disconcerting at first. I guess it does make sense though.

That said, I still found a bug here. If I try to find `backers.md` (in the `oni` repo), it properly shows `BACKERS.md` as the first suggestion, but it is not highlighted. I'll create an issue for that.
