### ISSUE TITLE
Highlighting in Quick Open doesn't work properly in case insensitive mode

### ISSUE THREAD

**Issue by rgehan** [onivim/oni#1828]
**How to reproduce**
- Open the `oni` repo
- `Cmd+P` and search for `backers.md` (lowercase)

**What happens**
- The `BACKERS.md` file is the first suggested, as expected, but it is not highlighted properly (see screenshot)

![capture d ecran 2018-03-16 a 22 21 56](https://user-images.githubusercontent.com/793402/37545298-ae084a4c-2968-11e8-9378-ff9199dfa1b1.png)

**Comment by bryphe** [comment]
Ah yes - the problem here is our highlighting logic is _independent_ of the matching logic (unfortunately). 

If we move to bringing over a scoring algorithm, like in #1828, that will provide the match positions - so we could use that to have accurate highlighting, instead of the heuristic we have today which isn't accurate.
