### ISSUE TITLE
How far can I go in using macros?

### ISSUE THREAD

**Issue by MartanLV** [onivim/oni#1837]
This project looks promising.

I met a problem recording macro that did work in `nvim`, but not in `oni`
### how to reproduce
- have two buffers open
- `qq<c-^>q` to record in @q an switch to recent buffer.
- or `qq0yf,<c-^>:g/<c-r>0/d<cr><c-^>jq` to illustrate the actual use case

So buffer switch is not replayed and `<c-r>0` didn't work also (to paste register content in command mode)

p.s. also from command line running `oni .` explorer would not point me to that direcrory, how so?

**Comment by CrossR** [comment]
Hey,

You should be able to do everything you can in nvim with macros, if you can't then its a bug!
What version of Oni are you running? We did just recently fix a bug with macros, so its possible that is causing part of this.

The paste regsiter issue sounds like we haven't correctly captured that command for the externalised commandline input, which I think is a bug.

If you want, you could do one of two things until the bug is fixed:
 * Disable the pretty looking externalised commandline and go back to the regular vim one with `"commandline.mode": false,` in your oni config.
* The less Vim way - Oni does have options to sync yanks with your system clipboard, so `Ctrl-v` would have pasted the same thing with that enabled, so the same affect could be achieved, albiet with different muscle memory. This defaults to enabled for yanks, and can be turned on for deletes.

**Comment by MartanLV** [comment]
Thank you for such a quick response.
I was on version `0.3.0` when reported this issue (as that is the one brew-cask gave me, thou not the latest). Just tested this on `0.3.1` and you are right, buffer switch *does* replays via macro now (also when config is `"tabs.mode": "buffers",`), and a paste register content in command mode also *does work*  for me now, even with the option set to `"commandline.mode": true,`.  Also now when oni is invoked from cli: `oni .` explorer does point to that pwd now.
So none of things I reported above seems to be irrelevant now.

My current set up is:
 - NVIM v0.2.3-dev (a.k.a. nightly)
 - oni 0.3.1
 - osx (updated)

**Comment by CrossR** [comment]
At least its all working now then!

Since this seems to be sorted, I'll close this out, but if you have any other issues, you can raise a new ticket.

Broadly, if its possible in n/vim it should be possible here, and we'd like to know the bits where that isn't the case, so we can see why. Or just other issues/features/etc.
