### ISSUE TITLE
Can't use numbers in Oni menus

### ISSUE THREAD

**Issue by CrossR** [onivim/oni#1842]
If I use numbers in an Oni menu, there is an error, which causes all of Oni to crash.
Its due to the highlighting expecting a string, and instead receiving a number and calling split on that.

I've got a PR (and attempted some React tests @Akin909!) ready to fix this first bit, but does it make more sense to just set the non-string object to `""` or attempt a `.toString()`? Feels like we should assume they give a string, and fail otherwise, since attempting to stringify could leave us in a bad state if we get an object.

Second issue here I guess is potentially why a `.split("")` manages to take out the entire UI.

Example:

```
var makeTestMenu = function () {
        var testMenu = oni.menu.create();
        var menuItems = [
            {
                icon: "window-restore",
                detail: 2,
                label: 1
            },
            {
                icon: "window-restore",
                detail: 2,
                label: 2
            }
        ];
        testMenu.show();
        testMenu.setItems(menuItems);
        testMenu.onItemSelected.subscribe(function (menuItem) {
            if (menuItem) {
                console.log(menuItem.detail);
            }
        });
    };
    oni.input.bind("<s-c-x>", makeTestMenu);
```

**Comment by Akin909** [comment]
@CrossR 👍cool re react test it'd be excellent to get more in the ones I started with were a little simplistic and more examples than anything else 😆, re the menu (my two cents) I agree re enforcing a string type (although plugins could be in `js` so no real certainty) re the error if its uncaught it probably propagates all the way up because the menu is outside of the editor window errorboundary so a menu error has the potential to kill the whole app
