### ISSUE TITLE
vim-plug with Oni

### ISSUE THREAD

**Issue by mjedmonds** [onivim/oni#1853]
Hi, this should be a relatively simple question but I don't find anything mentioned on the plugin documentation.

I use vim-plug (https://github.com/junegunn/vim-plug) as my plugin manager for neovim. I'd like to do the same for Oni. However, vim-plug says to place `plug.vim` in the `autoload` folder. Does Oni have a corresponding autoload? When I point my init.vim to my neovim version, `plug#begin` shows as an unknown function (meaning Oni's neovim instance isn't picking up the autoload folder).

Any ideas? If I make an `autoload` folder in `.oni`, will it be picked up like `plugin`?

**Comment by city41** [comment]
fwiw, I also use vim-plug and it is working well for me in Oni. My autoload is located at `~/.config/nvim/autoload`. In my Oni config, when I set `"oni.loadInitVim": true`, it loads all the plugins I've got in my init.vim. Other than turning on loadInitVim, I didn't do anything special for Oni.

I'm on Oni 0.3.1

**Comment by CrossR** [comment]
Sorry for the late reply!

The above is true, you should just be able to put it in the default location for your platform (`%LOCALAPPDATA%/nvim/autoload` on Windows, `~/.config/nvim/autoload` otherwise) and enable `"oni.loadInitVim": true` to have it work.

If you wanted some oni specific stuff, you can use `if exists('g:gui_oni')` or `if !exists('g:gui_oni')` in your `init.vim`, to either specify an Oni specific install dir, or Oni specific/excluded plugins.

**Comment by mjedmonds** [comment]
Thank you! My neovim configuration just sourced ~/.vimrc, but once I populated ~/.config/nvim it works as expected.
