### ISSUE TITLE
map <f3><esc>:tabe<cr> creates the map, but does seemingly nothing when f3 is pressed

### ISSUE THREAD

**Issue by hboon** [onivim/oni#1913]
This worked in v0.3.0, but stopped working in v0.3.1.

`map <f3>` verifies that the mapping is created.

Ditto for `<f2>`.
`<f1>`, `<f4>` works though.

**Comment by CrossR** [comment]
To my knowledge, both of those are bound to Oni commands (rename and formatting), which if you want to rebind you'd do as follows in your config file:

```
oni.input.unbind("<f3>")
oni.input.unbind("<f2>")

// Optionally rebind the commands, if you use them
oni.input.bind("<c-s-w>", "editor.rename")
oni.input.bind("<c-s-n>", "language.format")
```

Currently, Oni is swallowing the input, which would explain why this has happened.
If you have already unbound them, its a bug....you should be able to bind them all.

**Comment by hboon** [comment]
Ah. Works after unbinding them. Thanks.

In the interest of learning to fish.., how do I fetch the list of bindings and list of commands (or where do I dig to figure this out? It doesn't seem to be at https://github.com/onivim/oni/wiki/Configuration or the other pages in the Wiki)

**Comment by CrossR** [comment]
The bindings can be found here : https://github.com/onivim/oni/wiki/Shortcuts, and it should be relatively up-to date.
As for the commands, I'm not honestly sure...There was a list on the Wiki but since its been migrated I can't find it. I'll have a look around, and its possible there is a command you can run to list them all.

**Comment by hboon** [comment]
Wonderful. Thanks!
