### ISSUE TITLE
enhancement: browser url needs to be prefixed with "http/https"

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#1951]
Wanted to try out the `browser` 🎉 @bryphe it is amazing,
in the interest of providing possibly useful feed back one of the first things I noted was that I tried to type `www.google.com` in the address bar but this failed with a cannot get resource. 

I tried again with `https://google.com` which works fine. I think it could just be me but my instinctive response was to use the address bar in the same sloppy fashion in which I use google chrome. I'm wondering based on the implementation if its possible to check for a starting `https` or `http` and if not present then to prefix the address which is searched?

**Comment by bryphe** [comment]
> Wanted to try out the browser 🎉 @bryphe it is amazing,

Awesome! Thanks for trying it out 👍 

> I'm wondering based on the implementation if its possible to check for a starting https or http and if not present then to prefix the address which is searched?

Definitely. There are two places where we set the address in this file:
https://github.com/onivim/oni/blob/5678f045df06acdb80a3ff6e26c1f8a9c082c648/browser/src/Services/Browser/BrowserView.tsx#L184

`this._webviewElement.src = ...` is the code that applies the URL.

It'd be great to have a sanitizer / helper method so that we could pre-pend an `http://` if it isn't there!
