### ISSUE TITLE
Pressing tab does not complete autocompletion but inserts a tab instead

### ISSUE THREAD

**Issue by dlee** [onivim/oni#1959]
According to https://github.com/onivim/oni/wiki/Shortcuts#auto-completion, pressing <tab> should select the autocompletion option, but it inserts a tab instead.

I'm currently using the following override in my `init.vim`:
```vimrc
inoremap <silent> <tab> <C-o>:call OniCommand('contextMenu.select')<CR>
```
However, this prevents me from using tab to insert an indent when there is no completion menu.

The default behavior should be fixed so that it aligns with what the wiki says and allows to use tab as both indent and completion depending on whether there's a completion menu visible. In fact, it would be better if during completion, it cycled through the options.

**Comment by Akin909** [comment]
@dlee in order to complete with tab I have the following mapping in my `config.tsx`
```js
oni.input.bind(["<enter>", "<tab>"], "contextMenu.select");
```
This works to allow both using tab to indent and to complete.
Re. tab to cycle through I agree, not sure what other people's feelings on this are but we can use this issue to track perhaps switching the default behaviour as I think @bryphe was looking to replicate `vscodes` behaviour which I personally prefer vim's over

**Comment by badosu** [comment]
As @Akin909 pointed out, most vim user's will prefer to add tabs in the middle of an edit instead of opening the autocomplete menu. Since this is an easy enough snippet to put in your configuration I am closing this one.

For further reference a wiki page or configuration option can be provided if this seems like a big enough issue.

**Comment by OthmanEmpire** [comment]
A year into the future, and this issue was driving me crazy. 

As per @badosu solution, after referring to the Oni API, I added the following line into my Oni `config.tsx`: 

`oni.input.bind("<tab>", () => oni.snippets.insertSnippet("    "))`

which worked but it didn't allow for successive insertions of TABs quickly. Unfortunately the sequence of keys to insert multiple TABs would be: (TAB, ESC, a) then again (TAB, ESC, a).

I accidentally found another solution that worked for my needs. Hitting CTRL+SHIFT+TAB inserts a TAB regardless of whether the autocomplete menu appears or not. I'm leaving this solution here in case someone else like me needs it...
