### ISSUE TITLE
Clicking a link in the markdown preview opens the page in the entire oni window

### ISSUE THREAD

**Issue by Muream** [onivim/oni#2021]
This is my entire oni window after clicking on a link in the markdown preview:  
![image](https://user-images.githubusercontent.com/3117205/38246263-84ed7308-3741-11e8-90d3-c595021c4300.png)

I can't do anything but close oni and re-open it (the command palette doesn't work).

I think it should either open the link in a browser split or use the default browser.

**Comment by bryphe** [comment]
Ah nice catch, @muream ! Yes, this definitely should not happen... it's a bad bug because it paves the whole editing experience (and potentially means losing changes...)

Ideally, this should execute a `browser.openUrl` command - if the embedded browser is available, we'd open in that, otherwise we'd open it externally.
