### ISSUE TITLE
Tutorial Proposal: Copy and Pasting - `y`, `p`

### ISSUE THREAD

**Issue by keforbes** [onivim/oni#2035]
Building on the `d` delete tutorial and `w` motion tutorial explaining "nouns" and "verbs", we should have a tutorial for copy and pasting.  Possible commands should include:
`yw` - yank a word
`yy` - yank a line
`p` - paste after cursor
`P` - paste before cursor
`dw` -> `p` - show deleted characters go into paste buffer

Note that `p` and `P` are most easily understood when pasting lines.

**Comment by bryphe** [comment]
Great suggestion @keforbes ! Might be a good place to introduce `xp` (transpose a character)  and `ddp` (transpose a line), too.

**Comment by keforbes** [comment]
Good ideas, we should definitely include those features as well.  I'm hoping I can help implement some of these tutorials myself; the API you made for them seems pretty straightforward.  After Copy and Pasting I'd like to add a Visual Mode tutorial but I don't know if it's worth creating a separate issue for that; I'm hoping I can implement both.

You guys did a phenomenal job on this feature by the way; it's truly amazing.  I went a couple months without paying attention to Oni then I come back to find this incredible tutorial page with great visual feedback.  Well done!

**Comment by bryphe** [comment]
> You guys did a phenomenal job on this feature by the way; it's truly amazing. I went a couple months without paying attention to Oni then I come back to find this incredible tutorial page with great visual feedback. Well done!

Thanks @keforbes ! 👍 Good to see you again and glad you like the feature! I think there is a lot of potential for us to "lower the bar" to modal editing with a bit more content... and maybe some fun vimgolf stuff down the road.

> Visual Mode tutorial but I don't know if it's worth creating a separate issue for that;

A visual mode tutorial would be excellent. It would showcase / explain how "selection" (which is really just visual mode) in Oni is different from other editors. Plus showing off some of the powerful stuff like blockwise visual mode would be neat.

Might be worth having a separate issue for it, just because people might comment with some ideas.

> I'm hoping I can implement both.

That would be awesome! 😃 Hit me up if you have any questions.

**Comment by keforbes** [comment]
> Plus showing off some of the powerful stuff like blockwise visual mode would be neat.

Personally, I think blockwise visual mode should come in a later tutorial.  I'm thinking advanced tutorials would include things like: blockwise visual mode, named registers, marks, and macros.  I want to do basic visual mode next because I think it builds on the Copy & Paste tutorial since you can delete, copy and paste visually-selected text.

**Comment by keforbes** [comment]
Copy & Paste tutorial has been merged in (#2045).
