### ISSUE TITLE
Regression: File-explorer drag and drop

### ISSUE THREAD

**Issue by Akin909** [onivim/oni#2070]
Dragging and dropping in the file explorer, doesn't appear to be working anymore.
I think this might be as a result of other dragging and dropping in oni. While working on #1406, I noted that there's a bit of a delicate balance between the dragging files onto oni and the file explorer drag and drop as higher level events can swallow the event transmission.

I think if `stopPropagation()` is being called on `document.body` then this will prevent events being transmitted down to the file explorer.

In the long run I think all drag and drop functionality needs to be specifically scoped to target elements and events on body should be avoided aka `querySelector(.active .editor).addEventListener("drop...)` as opposed to more general handlers

**Comment by bryphe** [comment]
Thanks for logging this @Akin909 !

Interesting, it might be helpful to factor the drag-and-drop functionality to a component, as opposed to having it live on `document.body`. It'd be nice if we had a component like:
`<FileDropHandler onDrop={(files) => { ...do stuff to files...}} />`

We could put that on the `NeovimSurface` here - https://github.com/onivim/oni/blob/2b86676c80a67b8290cbf77eab23d49cc49d5ead/browser/src/Editor/NeovimEditor/NeovimSurface.tsx#L109

And plumb through an event handler so that the `NeovimEditor` can still handle it in essentially the same way. I think that would play a bit nicer with other drag/drop gestures, since it wouldn't be in the global event propagation path.

That would mean that we no longer need to hook `document.body.ondrop` in NeovimEditor.

The `document.body.ondrop` also has another problem in the multiplexed case (with `editor.split.mode` set to `oni`) - since in that case, we can have _multiple_ `NeovimEditor`s, dropping on a particular editor wouldn't always behave correctly, as there would be contention for handling that event.
