### ISSUE TITLE
Run ex commands at bottom of window like normal vim?

### ISSUE THREAD

**Issue by city41** [onivim/oni#2100]
When I first setup Oni I somehow managed to get it so that when I enter an ex command (for example `:s/foo/bar`, it would show up down below where it always does in regular vim.

But now, it always shows up in the little popup window in the top 1/4th of the window. Is it possible to get it to show up back in the traditional spot?

I searched the docs and issues and couldn't find anything about this.

**Comment by CrossR** [comment]
Sure! We do have some docs about it [here](https://github.com/onivim/oni/wiki/Configuration#externalised-command-line), but its always awkward to find something when the name isn't obvious.

Simply though, set `"commandline.mode": false,` in your `config.tsx`. You'll need to restart Oni since currently we pass those flags to neovim on startup, but we might be able to sort that soon.

**Comment by city41** [comment]
Awesome, thanks @CrossR , that did the trick.

**Comment by badosu** [comment]
@city41 See https://github.com/onivim/oni/wiki/How-To:-Minimal-Oni-Configuration if you find similar issues.

**Comment by city41** [comment]
adding `"commandline.mode": false` is no longer enough, also needed to add `"statusbar.enabled": false` to get this working with Oni 0.3.6.

Just a heads up for future readers.
