### ISSUE TITLE
QuickOpen - opening new buffer in same tab

### ISSUE THREAD

**Issue by stuffaboutpete** [onivim/oni#2135]
Apologies if I've missed some setting or documentation, but I don't seem to be able to work this out. I want to use the Quick Open menu to open a new buffer in the current tab. I know you can open a new split but I'm just looking for the equivalent of `:e FileName`.

The keyboard shortcuts listed [here](https://github.com/onivim/oni/wiki/Shortcuts), I think, imply that buffer should be the default behaviour as there is a specific shortcut for opening in a new tab. I get the same behaviour from hitting Enter as I do from hitting Ctrl-T. Is this a bug?

Love the project, keep up the good work.

**Comment by CrossR** [comment]
Hi!

Looks like the docs are out of date there sorry!, I'll try to get around to updating them today/this weekend.
That said, `Ctrl-Enter` sounds like what you want, which opens in the current buffer.

>I get the same behaviour from hitting Enter as I do from hitting Ctrl-T. Is this a bug?

Not a bug, just kinda redundant keybinds.... Oni has a `buffers` mode which opens every `buffer` in its own tab, rather than using vim tabs. `Ctrl-t` is useful there, but for the default, you are right it just duplicates the functionality of enter.

I do also have an open PR on swapping the default action (if that is something you are interested in), I have just been a bit swamped with work at the mo so I've not managed to update it yet. (#2080).

**Comment by stuffaboutpete** [comment]
Perfect, that's exactly what I was looking for, thank you.

Yes, I now see why Ctrl-t would be useful in buffers mode. It's purely a documentation issue at this point. And changing the default behaviour would be useful for me. I'll keep an eye on that. Thanks.
