### ISSUE TITLE
opening using `oni <dir>` does not set the dir correctly

### ISSUE THREAD

**Issue by danielb2** [onivim/oni#2163]
`<dir>` appears to be sticky. So the first time I opened oni, it was in a specific dir. Unless I change the dir with `:cd <dir>` the dir appears to be sticky.

expected:

`oni .`  should use the `pwd` to set the dir correctly for example.

**Comment by justinmk** [comment]
That's not the same thing as your original request.

**Comment by danielb2** [comment]
Yes it is. I'm talking about opening oni with `oni <dir>` and it showing the explorer for that dir.

`oni .` is one example. If I start it like that now, it is remembering the last directory I did a `cd` to. I don't know where it's storing that, but it's not in the config dir.

**Comment by justinmk** [comment]
What directory are you starting from? Regardless of args. That's what should be the process directory.

**Comment by badosu** [comment]
I am not sure invoking oni without arguments should set the cwd. The reason is that users that for some reason don't have a shell-less command to run Oni would always open it in the `~` dir, e.g. starting a terminal and running Oni.

My suggestion would be to adhere to the following convention:

- `oni`: Opens Oni without specifying any dir, i.e. loads the last cwd remembered
- `oni <dir>`: Opens Oni with cwd set as `<dir>` (including `.`)

This way users have flexibility for both use cases.
