### ISSUE TITLE
Oni spawns 2 instances of neovim

### ISSUE THREAD

**Issue by hkupty** [onivim/oni#2178]
Hi, sorry if I'm pollutting the issues with yet another one related to process/performance, but I realized that Oni spawns two neovim processes. It seems to me that one of them will be largely ignored, but still this is something undesired I think.

If you look at the picture below, you'll see that the last two items are neovim instances. They're quite the same except for one having the `-u /opt/oni/resources/app/vim/noop.vim` flag.

![2018-05-07-090044_1434x1266_scrot](https://user-images.githubusercontent.com/2695819/39689211-3ef67048-51d6-11e8-8665-5e270879d1c1.png)

**Comment by Akin909** [comment]
@hkupty thanks for raising the issue 👍, it's actually intentional that oni creates more than once instance of neovim, there are quite a few use cases for this but the first which is likely what you're seeing is for oni's sidebar which though a gui actually uses neovim under the hood to allow for using vim bindings etc. going forward once it becomes stable another reason why oni would spawn more neovim instances relates to having oni window splits as opposed to neovim splits aka if you wanted to `vsplit` and the `split.mode` was set to `oni` it would create a more gui like split. Currently in neovim the only way to achieve a gui split (as these features have not yet been externalised by `neovim`) would be to create another neovim instance that shares the `shada` history so clipboard and register stuff is shared.

@bryphe  can correct me if i'm wrong but I think the overhead of running multiple instances of neovim is actually minimal given how performant neovim is at least compared to running a `language-server` etc.

**Comment by hkupty** [comment]
That makes sense. I thought it would be an issue.
Thanks  for the attention!
