### ISSUE TITLE
sidebar.width is ignored

### ISSUE THREAD

**Issue by keforbes** [onivim/oni#2205]
In the config, there's a default value of:
```
"sidebar.width": "50px"
```
Any attempt to change this value is ignored.  I tried searching the codebase for its use, and it isn't referenced anywhere.

Can we please add support for this option? That sidebar is too small for my preference.

**Comment by keforbes** [comment]
Aha, found the hard-coded value:
https://github.com/onivim/oni/blob/bfd84e63956c1150386d3244b8f050a0bfccf2e5/browser/src/Services/Sidebar/SidebarContentSplit.tsx#L85
Now I just need to figure out how to inject the config value to that line....

**Comment by Akin909** [comment]
@keforbes you can import an/the instance of configuration from `Configuration.ts`  then in the width: 200px replace that with `width: ${configuration.getValue("sidebar.width")}`

**Comment by Akin909** [comment]
I'm actually looking to add a command to increase and decrease the size of the sidebar soon hopefully not quite the dragging with the mouse because that harder just increasing and decreasing that number based on a function call

**Comment by badosu** [comment]
@Akin909 As far as I know, and tested, the `sidebar.width` configuration does not exists or does not have an effect when configured. At least on the latest stable release.

**Comment by Akin909** [comment]
@badosu it's [in the default config](https://github.com/onivim/oni/blob/master/browser/src/Services/Configuration/DefaultConfiguration.ts#L379) as an option its currently set to `50px`, but the value is hard coded to `200px` in the relevant component

**Comment by badosu** [comment]
@Akin909 I am aware of that, but as you can see on [SidebarSplit](https://github.com/onivim/oni/blob/e92115daab1cdf299554b76f1300806d33f24f1c/browser/src/Services/Sidebar/SidebarSplit.tsx#L30) and [SidebarView](https://github.com/onivim/oni/blob/517280af3a1b30df84bec8f643bd20b111a7312c/browser/src/Services/Sidebar/SidebarView.tsx#L135) it is received as a prop that is never passed.

Unless I am missing somewhere else, this configuration is never used.

I am chiming in because this is the issue that annoys me the most and for longest using Oni, see also https://github.com/onivim/oni/issues/1414.

**Comment by Akin909** [comment]
@badosu apologies getting wires crossed I wasn't sure what you meant earlier I thought you meant that the key `sidebar.width` didnt exist in the config but you and @keforbes are right it isn't hooked up at all. I had a brief look last night and tweaking the component he pointed to works though if theres already been a prop which should represent the width somewhere then passing that would be much preferable to injecting the config in like that since we dont do that anywhere else in that way, was more of half baked than a full fledged solution

**Comment by keforbes** [comment]
I'm still hoping I can fix this issue even though most of this conversation is going over my head.  So where *should* the config value be injected? `ISidebarViewProps`? `ISidebarState`?

**Comment by badosu** [comment]
@keforbes I inspected the elements with the developer tools and seems like your first hunch is right, `SidebarContentWrapper` is the one controlling the width, currently at `200px`.

If possible, may I suggest you, when changing this to replace the default unit measurement from pixels to em or another scalable unit. Currently 200px is too small for high-resolution displays.

**Comment by keforbes** [comment]
Yes, I was able to tweak that value to confirm it affects the size.  But from what I could understand of your conversation with @Akin909, I shouldn't just replace that hard-coded value with `${configuration.getValue("sidebar.width")}`.  I thought you guys were saying I should set the config value to a key in one of those `props` objects and then access the `props` value in `SidebarContentWrapper`.  That's where I'm confused.

**Comment by badosu** [comment]
@keforbes That was a bad assessment from my part, I got confused with the width props inside `SidebarView` and mistakenly thought it was the part controlling it. With regard to the approach, I am not qualified to tell a better method.

**Comment by badosu** [comment]
One possibility is that the intended was to `sidebar.width` to control that and it may have been at some point, but with different content providers for the sidebar it was refactored and this is a legacy artifact.
