### ISSUE TITLE
Improve notifications appearance

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2233]
Oni Version: 0.3.4
Neovim Version (Linux only): 0.2.2
Operating System: Arch

#### Describe your issue

Notification messages are hard to read, they pop up on the right top corner without any margin and have a square-ish dimension.

See:

![screenshot from 2018-05-21 09-35-15](https://user-images.githubusercontent.com/347552/40307877-8813f49e-5cda-11e8-9142-dc09fa622102.png)

Btw, this is on a vertical split, so the lack of margin is actually a bigger issue than what's represented. This is probably due to a px sized margin instead of a scalable unit in a HiDPI display.

**Comment by keforbes** [comment]
Looks like it's defined here:
https://github.com/onivim/oni/blob/18f8546d88025718cf893f9f1b23fa16b067ce04/browser/src/Services/Notifications/NotificationsView.tsx#L41
It's using `rem` which *should* be scalable.  We might just need to be more forgiving with the `max-width` since it is a **maximum**.

**Comment by badosu** [comment]
@keforbes Thanks for the tip, was really helpful!

**Comment by Akin909** [comment]
@badosu @keforbes we discussed the sizes of the notification when we initially implemented it and @CrossR had a try with the sizes as I think initially it was too rectangular so I'd be careful there as changes to fix one view port might make it too big on another it might be worth looking at `vw` instead of `rem` or maybe `em`

**Comment by badosu** [comment]
@keforbes @Akin909 I tried your suggestion and it looks good on other machines, please review!
