### ISSUE TITLE
Webgl renderer: Blank screen after scrolling pages

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2234]
Oni Version: 0.3.4
Neovim Version (Linux only): 0.2.2
Operating System: Arch

#### Describe your issue

After scrolling down some pages, for some reason the screen gets blank and all characters are transparent except for the cursor.

#### Expected behaviour

Renders normally.

#### Actual behaviour

Selected in visual mode to emphasize:

![screenshot from 2018-05-21 22-02-43](https://user-images.githubusercontent.com/347552/40336916-bbfc109e-5d42-11e8-86da-1881d7117fe0.png)

Developer Tools:

![screenshot from 2018-05-21 22-00-33](https://user-images.githubusercontent.com/347552/40336922-c62ffbf2-5d42-11e8-9e67-bd5429d62f17.png)

#### Steps to reproduce

Not sure, just scrolled down a particular file.

**Comment by Cryza** [comment]
Thanks for reporting this ussue, @badosu!

In fact, we already have a fix for this issue in `master`. It will be released with the next patch version.

The PR that fixed it was #2198.
If you want to have the fix right now, you can always check out the repo and build the latest version from master yourself.

I'll close the issue now since this should be fixed. Please notify us if it still isn't fixed for you on `master`.

**Comment by badosu** [comment]
Ok @Cryza, I was not aware, thanks!
