### ISSUE TITLE
cmdline complete

### ISSUE THREAD

**Issue by meijieru** [onivim/oni#2258]
Oni Version: 3.4.0
Neovim Version (Linux only): 0.2.2
Operating System: linux

#### Describe your issue

In command mode, enter `ec<tab>`, nvim at terminal will show `echo echoerr ...` which overwrite the status line, while oni does not.

#### Expected behaviour

oni should also show the complete list

**Comment by meijieru** [comment]
@Akin909 I turn of the externalization. If cmdline is externalized, it works very well

**Comment by Akin909** [comment]
@meijieru is it alright to close this if its resolved?

**Comment by meijieru** [comment]
I still regard it as a bug as its inconsistent behavior with TUI. Someone may disable the externalisation for consistence with TUI.

**Comment by Akin909** [comment]
@meijieru in which case I'll reopen this to track that the wild menu does not work correctly if externalisation is deactivated. I just tried deactivating it locally and it wouldn't seem to turn off (first time since it was externalised I actually turned it off)

**Comment by CrossR** [comment]
The bug looks to be that you need to disable both ie:

```
"commandline.mode": false,
"wildmenu.mode": false,
```

Whereas, in reality I think `commandline` being `false` should imply `wildmenu` is also false.
Setting both to false results in:

![image](https://user-images.githubusercontent.com/10038688/40709937-47b2341c-63ef-11e8-82a9-59822f298276.png)

**Comment by CrossR** [comment]
After thinking about this, I think its okay to have options for both, that way a user can pick and choose what parts of this they want. Setting both to false gives the user the TUI they expect, and both to true gives the Oni experience.

When we add documentation for the config options, this should be made clear though, so the user knows to disable both.

I guess the only "bug" could be that you can't have the terminal commandline + externalised wildmenu, assumedly because there is no menu for the wildmenu to be rendered under.

I'll close this out for now, since I think that is a pretty niche choice, but if not we can always re-open this and add it.
