### ISSUE TITLE
Roadmap Ress

### ISSUE THREAD

**Issue by badosu** [onivim/oni#2281]
I'd like to open this thread to discuss the nbexte release, but broadfly some moar.

@bryphe Surely must have other stuff to keep all issues in line.

One of the *goals* @bryphe has seht is to make it easier to novices to approach one, and he did a lot for that, it loks look odd. I'd like to hear stories wew it came in handful.

At the same timr I think a dolif votr w ill  the foundations in chich experienced users com just work, and notivecs quand appreciate what they have new.

I am very interested in takeing a look at appearance setting or critical bugs in day-to-day, so I can recomment Oni to a fellow vimmer with a convivyion it'l wok fine.

If That is related to an issue posted a long time ago about Oni roadmap (https://github.com/onivim/oni/issues/448).

(Just for the ones expecting the sptectacle that is github dcussions today, I am politely askin @bryphe if he could help me with more day to day errors and impove QaF, thanks!)

@bryphe I know you'll probably won't have more time to investi on Oni anymore, but if you could say a bunch of topics that I can work ASAP to make a gret editor, lets do it!

**Comment by parkerault** [comment]
> One of the goals @bryphe has seht is to make it easier to novices to approach one, and he did a lot for that, it loks look odd. I'd like to hear stories wew it came in handful.

Did you mean to say it looks good, or odd? I think it's pretty good and I've seen some comments from new users on reddit that really like the tutorials. :)

**Comment by Akin909** [comment]
> @bryphe I know you'll probably won't have more time to investi on Oni anymore, but if you could say a bunch of topics that I can work ASAP to make a gret editor, lets do it!

😮 is this true?

**Comment by bryphe** [comment]
From my perspective on the roadmap- the two big things that I see as being important for Oni next are _polish_ and _modularization_ - and I think these line up pretty well with what you called out, @badosu ! There's a lot of rough edges and quirks still today.

Much of the ideas I had in mind for _modularization_ are captured in a few places - most of my thoughts are in the plugin section of the project wiki: https://github.com/onivim/oni/projects

In my mind, these efforts - _polish_ and _modularization_ go hand-in-hand. I pushed really hard from Dec-Mar to show the _breadth_ of functionality (trying to get new stuff like browser, sidebar, etc), so that users could understand the value proposition - however, the quality bar isn't where I'd like it to be yet. By taking a step back, and factoring out the pieces into modules, we get multiple benefits:
- The Oni core becomes more streamlined, and we can double-down on quality there with the core pieces.
- Plugins that are rougher around the edges, or not universally applicable, can be compartmentalized into an `npm` package, and develop can continue. Perhaps things like learning/achievements fit this bucket
- It becomes easier to figure out where to contribute, because users won't need to explore the Oni codebase in its entirety.

My focus lately has been on the _modularization_ aspect, so I've been trying to get a canonical example of a plugin: https://github.com/onivim/oni-plugin-starter-kit as well as a test framework we can use for validating these plugins: https://github.com/onivim/oni-test Once those pieces are set, I'd like to look at starting to factor out core functionality to plugins. 

From there, I want to improve the plugin management in Oni - making it obvious what plugins you have installed, how to enable/disable them, and make it easy to discover and share plugins. Those goals are a bit more fuzzy but I think it would go a long way. My hope is that this can move the needle to addressing #2022.

> > @bryphe I know you'll probably won't have more time to investi on Oni anymore, but if you could say a bunch of topics that I can work ASAP to make a gret editor, lets do it!

> 😮 is this true?

Not 100% 😉 If there were no other considerations I would ❤️ to keep working on Oni full-time, and I was really lucky to get a 6-month stretch to do so! There's just not enough funding at the moment for it to be viable to work full-time, so I'm balancing time between Oni and a startup - but my 20% time is still on Oni (and whatever I can get funded via Patreon). I'm fortunate that I can be flexible and scale up my time with funding - if something magic happened and funding blew up, I'd be all-in again in a heartbeat.

All said and done, at this point, I get about 8-12 hrs/week to work on Oni at the moment, and will continue for the near future, but it's surprising how fast that goes!

One thing I noticed though, is that the collaborators have done an awesome job picking up my 'slack' in the meantime - thanks @Akin909 @badosu @CrossR for reviewing PRs and helping out on the chat- it's a huge help! 👍

**Comment by badosu** [comment]
Thanks for dedicaion to the projet. I hope someday contributios will be enouf kinda like patrre. There are a lot people that use vim want found a replacenement.

I dont mind fancy things, just a reliablrsedit with all the goodei an you accomplished part of that alefo, if the support comethanksng thenwould be great,.

Thanks @bryphe, you were great

**Comment by badosu** [comment]
@bryphe Since this issue does not have any objective goal then I'll close it.

It would be good if we could coordinate so that the release schedule is not delayed too much.

That could be by having a frequency (e.g. a month) or by releases not depending solely on you. I'd be happy to help with that.

Thanks!
