### ISSUE TITLE
Can't get spellchecking to work with :set spell

### ISSUE THREAD

**Issue by kropper** [onivim/oni#2308]
Oni Version: 0.3.4
Neovim Version (Linux only):
Operating System: macOS

#### Describe your issue

I try to activate spellchecking with ```:set spell``` for a buffer, and it tells me it's in spellchecking mode (with the appropriate language, as configured in ```init.vim```), but it does not highlight misspellled worz.

#### Expected behaviour

Make misspelled words visible and navigable like in other neovim GUIs.

#### Actual behaviour

Behaves as if ```set spell``` was not executed, although showing it in the mode line.

#### Steps to reproduce

Open any text file, run ```:set spell```.

This likely is a stupid error on my side, and eventually should be an FAQ, but I didn't find anything about Oni related to spellchecking.

**Comment by CrossR** [comment]
Hey, I think this is already covered over in #1931.

As far as I can tell, its due to Oni not currently drawing underlines and undercurls (or whatever the wiggly underlines are called).

Themes that don't use underlines for spelling mistakes work fine, but themes that use some form of underline will fail. I've posted a comparison between `onedark` and `nord` at the bottom  of that thread, where `onedark` works fine but `nord` fails.

I had a quick look at adding this for the new WebGL renderer, but didn't get very far.... @Cryza do you know how easy this would be to add? Oni already knows all about both underlines and undercurls, its just a case of drawing them.

**Comment by kropper** [comment]
Thank you, that's it! Looking forward to updates. :-) Keep up the great work!!
