### ISSUE TITLE
Cannot edit config

### ISSUE THREAD

**Issue by SamHH** [onivim/oni#2310]
Oni Version: 0.3.4
Neovim Version (Linux only): 0.3.0
Operating System: Arch

---

When I enter the settings, I am unable to edit them. So I set modifiable with `:set ma`.

I am then unable to save my settings due to the following error: `E382: Cannot write, 'buftype' option is set`. So I set `:set buftype: " "` as an attempted workaround.

This allows me to save within the UI, however the changes (e.g. font size) don't take effect, and when I fully restart Oni it transpires that the config has not changed at all.

---

I've tested emptying my `init.vim` of all but `set number` just to be sure my Neovim config wasn't interfering and the issue persists. I've also tried emptying `shada/` and `swap/` in `~/.local/share/nvim/`.

I _am_ able to write to a regular file e.g. `:w file.txt` (without any of the workarounds above).

**Comment by CrossR** [comment]
Hi!

Just to be sure, when you are attempting to edit your config, you are attempting to edit the file on the right, not the left?

(I've put mine as an example below)

![image](https://user-images.githubusercontent.com/10038688/41258669-f38eb354-6dc8-11e8-8149-9c0998705f29.png)

The left side shows the current value, the right side shows your actual config. The left is non-modifiable and a few other things.

I know quite a few people have tried to edit the config reference due to it not exactly being obvious right now... In the future, the reference should have a comment at the top explaining what it is, and then some descriptions for each of the config options, so its a lot more obvious.

**Comment by SamHH** [comment]
Oh dear... that is an embarrassing mistake... haha!

For what it's worth I expected to be able to edit it due to my familiarity with VSCode.

**Comment by CrossR** [comment]
Lots of people have done it, so its definitely an Oni problem!

Ideally for me, we'd mirror the VSCode experience, that is:

- A description/explanation at the top to make it much clearer.
- Comments for every config option.
- Keybind to copy a config option over to your config.
- Auto complete for the options where appropriate.
