### ISSUE TITLE
[Feature request] Sublime style indentation guides

### ISSUE THREAD

**Issue by sullyj3** [onivim/oni#2316]
I can `listchars=tab:| `, but it's ugly. I'd rather it look like sublime:

![Sublime indentation guides](https://wesbos.com/wp-content/uploads/2013/07/ss-2013-07-24-at-4.02.52-PM.png)

**Comment by CrossR** [comment]
I raised this a while back, 2 things I prefer in GUI editors is the show whitespace options (indent guides, spaces etc) and column rulers. Its over in #836 which doesn't have much activity.

However, PR #2188 was recently merged and looks to be the start of adding something like this!

I'll close this out and stick a comment in the other issue to check what is needed for this, since I'd love to remove my vim plugins I have for this that only get me part of the way to where I want to be.
