### ISSUE TITLE
devtools clipboard copy does not work

### ISSUE THREAD

**Issue by justinmk** [onivim/oni#2347]
**Oni Version:** 0.3.5 (and earlier)
**Neovim Version (Linux only):** 0.3.0
**Operating System:** macOS

**Issue:**

Copying text to clipboard doesn't work in devtools.

**Steps to reproduce:**

1. open devtools
2. select the Console tab
2. select some log text in the Console log
3. type cmd-c or ctrl-c, or select Edit ... Copy from the system menu. 
    - Also, right-click menu doesn't show Copy/Paste when text is selected.
4. Try to paste the text using the system clipboard (cmd-v or ctrl-v).

**Comment by bryphe** [comment]
Thanks for reporting the issue, @justinmk ! I can reproduce this on mac as well - strangely, it doesn't repro on Windows. 

I wonder if somehow our key handling logic is impacting this, but we shouldn't be able to interfere with any devtools events. It could also be the case that it's actually an electron bug - we should see if this reproduces with just a basic electron 2.0.2 project (like https://github.com/electron/electron-quick-start)

**Comment by psxpaul** [comment]
I believe this only effects macOS, and is caused by [this electron bug](https://github.com/electron/electron/issues/11998). My linux machine is not affected.

I have tried applying the workaround [this comment](https://github.com/electron/electron/issues/11998#issuecomment-370141085), and it appears to work. If this is a reasonable approach, I can open a pull request.

**Comment by Akin909** [comment]
@psxpaul that'd be awesome thanks for looking into it 👍 , as someone who has been developing on mac for months that would be a huge quality of life improvement, cant count the number of times I've tried to paste into and out of the dev tools in oni only to find it doesn't work ^^
