### ISSUE TITLE
Letter under cursor is not good / simple space is bigger

### ISSUE THREAD

**Issue by lauccode** [onivim/oni#2356]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):** 0.2.2
**Operating System:** MANJARO
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.1.10
DISTRIB_CODENAME=Hakoila
DISTRIB_DESCRIPTION="Manjaro Linux"

**Issue:**
For example, this line in cpp :
std::string ObstacleResultatVersString(ObstacleResultat r)
is looking with more spaces
And when you put cursor somewhere, you can see another letter
For example, if I put the cursor on the "u" of "result", I can the the R which is before...

**Expected behavior:**
no moving letter under cursor or word movement when moving cursor

**Actual behavior:**
As explained before

**Steps to reproduce:**
Just open and use oni after installation on MANJARO with the command:
yaourt -S --noconfirm oni

I will try to do a screencapture to watch how it is looking when I move cursor.
It should be a single space after the word "string".
![capture d ecran_2018-06-25_20-04-29](https://user-images.githubusercontent.com/36818928/41868057-3b70a2d0-78b5-11e8-9fef-7804261576ed.png)

**Comment by CrossR** [comment]
This occurs when the font Oni is using isn't valid, so you swap to some default that isn't monospace (not the best I know, I've had the same on Arch).

You'll want to add `"editor.fontFamily": "some_font_name",` to your `config.tsx` which you can find under `Ctrl-Shift-P` and user config. You'll get your config on the right and a reference buffer of the current config settings on the left which isn't modifiable. There is also `"ui.fontFamily"` but the UI doesn't matter as much since its not showing code.

The fix here is that we need to update the list of fonts to include something Arch/Manjaro etcetc has, or find some better way of ensuring a monospace font is picked, perhaps by including one ourself.

**Comment by lauccode** [comment]
Thanks it is working well with monospace.
