### ISSUE TITLE
Unable to launch NeoVim

### ISSUE THREAD

**Issue by FourSeventy** [onivim/oni#2387]
**Oni Version:**
0.3.6

**Neovim Version (Linux only):**
v0.3.0

**Operating System:**
MacOS El Capitan

**Issue:**
When I launch Oni I get the "Uh oh! Unable to launch Neovim" error even though I have nvim installed.

Here is my nvim --version output

```
~ $ nvim --version
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-41002-1capld4/neovim-0.3.0/build/config -I/tmp/neovim-20180612-41002-1capld4/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-41002-1capld4/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-41002-1capld4/neovim-0.3.0/build/include
Compiled by brew@ElCapitan-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```

**Comment by CrossR** [comment]
This looks like #2354 (I'm not a Mac guy so I could be getting my versions mixed up).

There is a bit of discussion going on in that issue, but I've stuck a temporary work around at the bottom of that issue on reverting to `0.2.2`, since something seems to have changed on the MacOS side with `0.3.0`, since no other platform is having issues. Even different installs of Oni seem to act differently (ie from source/real release) as each uses a different binary from nvim-core.

**Comment by FourSeventy** [comment]
Thanks. Sorry for the duplicate.
