### ISSUE TITLE
Any way to disable symbol search (Control+t) in Oni?

### ISSUE THREAD

**Issue by DougBeney** [onivim/oni#2410]
First of all, great program! Really liking it.

In terminal-based NeoVim, i had a shortcut for creating new tabs (Control+t). I see in Oni that Control+t is mapped to a symbol search. Any way to unmap that symbol search?

Also, how does symbol search work? In a C file I created a few functions and such. I'd imagine this feature is for navigating through those but I don't see any results populating in symbol search.

**Oni Version:** 0.3.6
**Neovim Version (Linux only):** NVIM v0.3.0
**Operating System:** Fedora 28

**Comment by CrossR** [comment]
Hey!

To unbind, you'd need to use `    oni.input.unbind("<c-t>")` in the activate part of your `config.tsx`. (Thats in File > Preferences > Oni Config, and its the split on the right, the left is your current settings which can't be modified directly.) If you wanted to keep the functionality around, but rebind it, you'd use something like `oni.input.bind("<s-c-w>", "language.symbols.workspace")`. You can see the full set of defaults, and what command they call over in https://github.com/onivim/oni/blob/master/browser/src/Input/KeyBindings.ts


The symbol search is actually power by having a language server on your machine for the current language.

We ship with Javascript/Typescript/Reason/OCaml support, and you can add extra LSP support by installing the relevant LSP for that language. You'll not be seeing something for C since we don't ship that LSP built in, rather you need to install it if you need it. There is an ongoing issue of actually swapping the check from silently failing to instead throwing up an info notification explaining that/giving links to the right LSP to install.

Can get some more info on all of that over in https://github.com/onivim/oni/wiki/Language-Support (or https://langserver.org/ for the general explanations/lists of LSPs).

**Comment by DougBeney** [comment]
Thanks for the fast reply. Will look into the language server stuff.
