### ISSUE TITLE
Truncated copy/paste

### ISSUE THREAD

**Issue by Piping** [onivim/oni#2414]
**Oni Version: **
**Operating System: windows**

**Issue:**
Copy a large number of lines into Oni and only got paste partially.

**Comment by CrossR** [comment]
Confirmed using the `csv` file we have in `test/collateral/`, copied the raw file from GitHub and pasted into Oni and got 975 lines and 1 partial line, rather than 1000 lines. Pasting into Notepad++ (to prove the file was fully copied) worked fine.

Copying/pasting directly inside Oni (with `y`/`p`) is fine, only copying from outside Oni and pasting in seems to be broken.

The way we read the clipboard (`clipboard.readText()`) seems to be the only way to do so, so I think the issue lies in the use of `nvim_input` rather than  `nvim_set_lines`?

**Comment by Akin909** [comment]
Hopefully this is a good first issue the related code is [`here`](https://github.com/onivim/oni/blob/e0aa2a556b3cc287cb932058d92440e8311a0d0f/browser/src/Editor/NeovimEditor/NeovimEditorCommands.ts#L68) I believe the steps to resolve this would be first confirming that `clipboard.readText()` isn't clipping the text if not then as @CrossR suggested I think switching to using `neovimInstance.setLines` would be preferable docs [here](https://neovim.io/doc/user/api.html)

It would be interesting to know why the `input` function is truncating the input as this maybe an issue we ought to raise with `neovim` or we might be using the method incorrectly

**Comment by psxpaul** [comment]
I took a quick look at this over the weekend, and here are a few things I found:

- `clipboard.readText()` is not clipping, but `neovimInstance.input(sanitizedText)` is. The documentation for `nvim_input()` [here](https://neovim.io/doc/user/api.html#nvim_input()) seems to indicate that clipping will occur if the buffer becomes full.
- Using \<c-v>/\<m-v> to paste even short text, then using the repeat operator (`.`) results in all pastes after the first one to have incorrect indentation. I believe this is because `set paste` and `set nopaste` are not invoked with the repeat operator.
- Using `nvim_buf_set_lines` like `BufferManager.setLines` would likely break the repeat operator in a different way. Issue #2501 has some more information on that.
- The Edit->Paste, Edit->Paste Line Before, and Edit->Paste Line After do not seem to suffer from the truncation issue. They are executing the `\\"+gP`, `[p`, `]p` commands respectively, instead of simulating user input.
- The Edit->Paste menu command seems to paste before the current cursor, which doesn't seem correct to me. At the very least, it is different from the \<c-v>/\<m-v> behavior.
- With the setting `"editor.clipboard.synchronizeYank": false`, \<c-v>/\<m-v> will do a vim yank, but not update the system clipboard. This seems weird to me as well, because I don't want normal yanks to stomp on my system clipboard, but I do want <c-c>/<m-c> to copy to the clipboard.

The simplest approach to me would be to change the `editor.clipboard.paste` command to just execute `"+p`, but from bryphe's comments in #628, the current approach was used to workaround issues with win32yank on Windows.

**Comment by Akin909** [comment]
@psxpaul thanks for investigating what was going on here and for the detailed feedback 👍, I think the `"+p` solution you mentioned would be the simplest and arguably best although I'm not sure how many people the win32yank issue (not sure I fully understand it from the linked issue) affects but atm the workaround seems to affect everyone and breaks pasting into oni 😞, meanwhile the `"+p` solution is the vim way of handling this issue

**Comment by CrossR** [comment]
It may be worth trying using `"+p` again, since we do include `win32yank` on Windows, and it works across my 3 machines.

Maybe added as a config option and the devs/insiders give it a try for a bit and then make it the default?

**Comment by psxpaul** [comment]
Can this be closed now?

**Comment by badosu** [comment]
@psxpaul Did you reproduce the error previously and confirm it is fixed now?

**Comment by CrossR** [comment]
I've tested the test case I gave and it is fixed for that, so I'll close this out now! Cheers @psxpaul !
