### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by binamkayastha** [onivim/oni#2464]
**Oni Version:** 0.3.6
**Operating System:** Mac High Sierra

**Issue:** When in :terminal mode, in ranger, ESC doesn't register in ranger (or other terminal programs, like running vim in :terminal mode), and goes to vim editing mode

**Expected behavior:** ESC should register in ranger (Testing in terminal version of neovim)

**Actual behavior:** ESC causes you to go to vim mode, making it impossible to esc out

**Steps to reproduce:** Just try and run vim in :terminal mode, and you'll see how the ESC is registered very confusingly.

I'd love to help work on this issue as well, but I have no idea where to start.

**Comment by CrossR** [comment]
This is most likely due to the Oni default config having this in it: https://github.com/onivim/oni/blob/b2ef17fde057d55eeb6ac78e1e3c0a73bd279c18/vim/default/bundle/oni-vim-defaults/plugin/init.vim#L21

You can disable the default config if you want (with `"oni.useDefaultConfig": false,`), which would stop this. Though, if you do that you may want to move some of the settings from the default config into any custom vim config you have. There is some more details on that at the bottom of: https://github.com/onivim/oni/wiki/How-To:-Minimal-Oni-Configuration

Ideally, we'd remove that entirely, and move the config into an Oni option, so its more easily changed.

**Comment by binamkayastha** [comment]
Thank you!!!
