### ISSUE TITLE
Vim fugitive not working on Oni

### ISSUE THREAD

**Issue by jamestthompson3** [onivim/oni#2480]
![fugitive](https://user-images.githubusercontent.com/19915504/43395481-e1f38cb4-9406-11e8-86ca-25edbf303d9d.gif)

**Oni Version:**
 0.3.6
**Neovim Version (Linux only):**
**Operating System:**
 Windows 10

**Issue:**
When running a vim-fugitive command such as `Gstatus` in neovim, everything works as expected, however in oni, the `not an editor command` error appears. I know that the plugin is being loaded correctly because `:help fugitive` brings up the manual page for the plugin.
**Expected behavior:**
Commands such as `Gblame`, `Gstatus`, etc. should correctly execute and bring up the status, blame, etc for the given project.
**Actual behavior:**
Errors out with message: `E492: Not an editor command: Gstatus`

**Steps to reproduce:**
Load [config](https://github.com/jamestthompson3/vimConfig) open any project with git version control and run any vim-fugitive command.

**Comment by Akin909** [comment]
@jamestthompson3 thanks for checking out Oni and posting the issue. I currently rely on `fugitive` and use it in oni although I haven't encountered this error, the error aka `E492` comes from neovim and we dont interact with it (fugitive or rather we dont intentionally) although it might be a question of how fugitive is setup on your machine, can I ask where is it installed via vim-plug etc. or is it in `/.config/oni/plugins/` ?

**Comment by jamestthompson3** [comment]
It is installed via [dein](https://github.com/Shougo/dein.vim).

**Comment by Akin909** [comment]
We've had an issue somewhere regarding some plugins and oni in dein and I believe Shougo the guy behind dein released a fix the issue was https://github.com/onivim/oni/issues/1163 and one of the solutions someone else 

posted was 
```vim
if !exists("g:gui_oni")
  call dein#save_state()
endif
```

can you see if that works or if upgrading dein changes anything

**Comment by jamestthompson3** [comment]
It just started working, I haven't done anything to modify oni or my vim config... I will try your solution and see if it becomes more stable.

**Comment by Akin909** [comment]
Is there a way to clear dein state could be that you have an old dein state saved? that precedes the update? I think dein caches the vim rtp which means that the rtp it uses doesn't match oni's for the nvim instance it spawns I'm not entirely clear on what the original issue was with dein

**Comment by jamestthompson3** [comment]
I checked the issue you mentioned. I have tried the following:
-cleared the dein state, updated remote plugins. 
-restarted oni and ran `dein#update()`
-deleted all plugins and ran a clean `dein#install()`

Nothing worked. Then after a while of using oni without fugitive working, it worked again, but then I closed my session, and when I opened oni again, fugitive is broken again.

**Comment by badosu** [comment]
@jamestthompson3 I use fugitive with vim daily and the error message you receive is very common, usually the cause is that the current buffer is not on a file inside a git tree.

Can you confirm if it still happens when editing a file controlled by git?

**Comment by jamestthompson3** [comment]
Can confirm. The fugitive support has continued to be off and on in the same directory. Sometimes when I start oni, it works as expected, other times, it doesn't.

**Comment by jamestthompson3** [comment]
I've noticed that this on again, off again pattern is present in other parts of oni, most notably the completion and LSP. Without any other completion or LSP plugins loaded ( only relying on what is available in `config.tsx` ), I've noticed that it just stops working after a few minutes.

**Comment by badosu** [comment]
@jamestthompson3 I've been using fugitive with Oni for a year and never had any issue, I am not sure how to reproduce your error.

This is my config:

<details><summary>init.vim</summary>
set nocompatible              " be iMproved, required
filetype off                  " required

set number
set noswapfile
set smartcase

" Turn off statusbar, because it is externalized
set noshowmode
set noruler
set laststatus=0
set noshowcmd

" Enable GUI mouse behavior
set mouse=a

set list
set listchars=trail:·

set diffopt+=vertical

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-vinegar'
Plugin 'tpope/vim-rhubarb'
Plugin 'airblade/vim-gitgutter'
Plugin 'KeitaNakamura/neodark.vim'
Plugin 'posva/vim-vue'

set sw=2
set ts=2
set softtabstop=2
set expandtab

nnoremap ,s :nohlsearch<CR>

call vundle#end()            " required
filetype plugin indent on    " required

colorscheme neodark

let g:neodark#background = '#202020'
</details>

<details><summary>config.tsx</summary>
import * as React from "react"
import * as Oni from "oni-api"

export const activate = (oni: Oni.Plugin.Api) => {
  oni.input.unbind("<c-v>")
}

export const deactivate = (oni: Oni.Plugin.Api) => {
}

export const configuration = {
    activate,
    deactivate,
    "oni.hideMenu": true, // Hide default menu, can be opened with <alt>
    "oni.loadInitVim": true, // Load user's init.vim
    "oni.useDefaultConfig": false, // Do not load Oni's init.vim
    "ui.colorscheme": "n/a", // Load init.vim colorscheme, remove this line if wants Oni's default
    "autoClosingPairs.enabled": false, // disable autoclosing pairs
    "commandline.mode": false, // Do not override commandline UI
    "wildmenu.mode": false, // Do not override wildmenu UI,
    "learning.enabled": false, // Turn off learning pane
    "achievements.enabled": false, // Turn off achievements tracking / UX
    "editor.textMateHighlighting.enabled": false, // Use vim syntax highlighting
    "editor.typingPrediction": false, // Wait for vim's confirmed typed characters, avoid edge cases
    "editor.fontSize": "34px",
    "ui.fontSize": "22px",
    "editor.fontFamily": "Inconsolata",
    "editor.renderer": "webgl",
    "ui.fontFamily": "Inconsolata",
    "sidebar.default.open": false,
}
</details>

**Comment by jamestthompson3** [comment]
Simplifying my vim configuration did the trick, seems to be working more reliably now. Thanks everyone!
