### ISSUE TITLE
vim-bdubs does not work with Oni

### ISSUE THREAD

**Issue by lowski** [onivim/oni#2484]
**Oni Version:**

0.3.6

**Operating System:**

MacOS

**Issue:**

Oni is not compatible with [vim-bdubs](https://github.com/jbranchaud/vim-bdubs). When I try to run `:BD` command raise an error.

**Expected behavior:**

It should close all other buffers except the currently open one.

**Actual behavior:**

It says: `not editor command: BD`.

**Steps to reproduce:**

Add [vim-bdubs](https://github.com/jbranchaud/vim-bdubs) to your Neovim config and try to execude `:BD` command from any open buffer.

**Comment by CrossR** [comment]
I've given it a quick try and it seems to work for me.
Could we get some more info on how you installed it?

Once thing that it could be (and we should probably surface to the user more) is that nvim is reloaded only on a full restart of Oni. On Linux and Windows that is fine, since Oni closes when you close it. But on macOS, since it closes to the dock, its a bit more awkward.
So, did you restart Oni after the install, either with `Cmd-Shift-P` and Reload Oni (which does a full reload) or with right clicking Oni in the dock, and then re-opening?

Thats just a guess, but it is a possible cause, since it sounds less like its not working, and more like its not installed/being found, since the command isn't appearing at all.

**Comment by lowski** [comment]
@CrossR so stupid of me. I was messing around with multiple vim configs at the same time so heavly that I forgot to install the plugin in new location 🤦‍♂️ . Sorry and thank you for checking this issue.

I'm closing it as it works as expected.
