### ISSUE TITLE
Oni doesn't suggest autocompletions while in comments or strings

### ISSUE THREAD

**Issue by jwmann** [onivim/oni#2500]
**Oni Version:** 0.3.6
**Operating System:** MacOS 10.13.6

**Issue:**
Completion Suggestion doesn't trigger while inside a string or comments. (tested in javascript files)

**Expected behavior:**
```
const fooBar = () => {}

// Function fooBar does x, y, z
console.log( "fooBar", { fooBar });
```
While typeing the comment or string of fooBar, I should get a suggestion to autocomplete the word fooBar as I'm typing it.

**Actual behavior:**
Nothing, I don't get any suggestions for strings or comments

**Steps to reproduce:**
`foobar.js`
```
const fooBar = () => {}

```
Type `console.log( "` then trying autocompleting "fooBar"

**Comment by jaredly** [comment]
Hah, I'm actually experiencing the opposite behavior on oni and I find it super annoying 😅

**Comment by Akin909** [comment]
@jwmann thanks for opening the issue @jaredly sorry your hitting the opposite case, re. the settings for completion I haven't had a close look at where we are setting that (although its probably in the lsp config options we have set) @bryphe would know best but we could hopefully just read the desired behaviour out of a user's config e.g. `config.completion.comments` since based on the feedback either option would be desirable

**Comment by badosu** [comment]
To be frank that makes sense, even though I found this behavior annoying when I used some IDEs. I am not sure how autocompletion is implemented, but if it comes from the LSP there's not much we can do.

As for @jaredly's issue, that's a bug. Do you still experience it? Would you care to create an issue elaborating it?
