### ISSUE TITLE
Oni completions are not dot repeatable

### ISSUE THREAD

**Issue by jwmann** [onivim/oni#2501]
**Oni Version:** 0.3.6
**Operating System:** MacOS 10.13.6

**Issue:**
When selecting a completion from the suggestion list, after autocompleting, it can't be dot repeatable

**Expected behavior:**
Autocomplete a word and dot repeat will insert the whole word again

**Actual behavior:**
The first word autocomplete and dot repeating will only insert the manually typed in portion of the completion

**Steps to reproduce:**
`const fooBar;`

1. Type `foo` a suggestion will appear
2. Press `<Enter>`, fooBar will be completed.
3. Press `.` and only `foo` will be repeated.

**Comment by CrossR** [comment]
I think this is covered over in #1200, but it is getting more and more on my nerves.

Its possible we just need to look into the nvim API a bit more and see if we can have macros replay msgpack calls, or have nvim core decode the msgpack call and have its contents as part of the macros.

I'll closes this out for now.

**Comment by vlcinsky** [comment]
Would https://github.com/tpope/vim-repeat apply here?

**Comment by jwmann** [comment]
@vlcinsky Maybe? I'm already using it but maybe it needs to be integrated on Oni's side internally

**Comment by Akin909** [comment]
I wonder if potential other solution could be that rather than having oni's autocomplete menu completely sidestep vim's popup we could actually just populate the vim's completion menu with the language server results like `nvim-typescript` or `deoplete` do that way all we do is populate a menu and vim is in control of inserting the text.

This could also make way for having vim and oni completion combined (but differentiated), though this sort of a change would definitely need some input from @bryphe as he may not like the idea?
