### ISSUE TITLE
Hey, so how do I create a colorscheme? my neovim terminal scheme isn't loading right.

### ISSUE THREAD

**Issue by youssoftaha** [onivim/oni#2540]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):** 0.3.1
**Operating System:** Manjaro(Hakoila) 17.1.2

**Issue:** How do I create a colorscheme supported by oni? my favorite colorscheme is [Preto](https://github.com/ewilazarus/preto) but it doesnt load in oni. I was wondering how to make my own

**Comment by Akin909** [comment]
@youssoftaha I've actually just stuck up a PR for an Oni port of https://marketplace.visualstudio.com/items?itemName=sdras.night-owl here -> https://github.com/onivim/oni/pull/2541 you can more or less copy that patter but swap out all references to night owl to preto and stick in the colors for preto in the json that what styles the actual oni sections, you can completely remove the "editorTokens" sections as that wont apply to you

**Comment by youssoftaha** [comment]
@Akin909 This is hillarious I was actually on ur pull request page 5 mins ago thibking the same, but then do I stick it into plugins folder?

**Comment by Akin909** [comment]
@youssoftaha you have two options if you want to make a theme you can make a PR to oni with the theme then others can use it they go in the extensions dir (ideally all themes would be independent and users could download them). The second option which is the longterm option is if you create your theme as a repo called `oni-theme-preto` but with the same content as would go in the extensions dir e.g

```
	package.json
	colors/
		preto.vim
		preto.json
```

this can clone into `~/.config/oni/themes/...`  and oni will pick it up.
Long term we plan on having an oni sidebar pane that allows users to automatically download themes

**Comment by youssoftaha** [comment]
@Akin909 Hey, So I copied the preto vim file into a colors directory and made a preto.json and a package json in the parent directory. Then I moved it into ~/.config/oni/themes/theme-preto. That didn't show up so I put it into /opt/oni/resources/app/extensions/theme-preto. It showed up eventually but the colors are nothing like neovim, however the json file seems to change the workbench colors correctly

**Comment by youssoftaha** [comment]
@Akin909 I did exactly that and this is what I got (keep in mind that there is a vim script for coloring the operators)
oni on the left and nvim on the right 
![screenshot](https://user-images.githubusercontent.com/42289530/44951030-fbb91080-ae26-11e8-8dfc-814944964f63.png)

**Comment by youssoftaha** [comment]
Wait so what is the purpose of a json file then?

**Comment by CrossR** [comment]
The JSON file is for the Oni UI, so you can specify the colours of the tab bars, explorer, status bar, quick open menu, highlights and so on. You can technically use it without one and Oni will just guess at some appropriate ones, but manually defining them usually gives a better look.

I think the colour differences may be due to the fact the plugin isn't setup correctly for neovim (see https://github.com/ewilazarus/preto/pull/3).

Applying the fix in that linked PR gives me something that looks like the image in the README:

![image](https://user-images.githubusercontent.com/10038688/44954419-acf88e80-ae99-11e8-95bb-629e857349bb.png)

So I think it should just be a case of applying that fix to your copy of the colour scheme, and then in the JSON file, copy over some colours from the vim file, such that the Oni UI looks a bit nicer. Ie currently in that screen shot I sent, the file tabs and tab backgrounds are the same colour, which makes them hard to distinguish. Similarly, the selected tab is the same colour as inactive ones, which makes it hard to distinguish and so on. The QuickOpen menu was also pretty dark etcetc.

You can do as much or as little in the JSON file as you need, but its probably a good idea to stick a colour in each, just since so many of them are used in more than one place. Ie the background is used in loads of places to be the background for a lot of the UI.

**Comment by youssoftaha** [comment]
Magnificent. Thanks for the digging, Im gonna play around with this for a
bit.

**Comment by youssoftaha** [comment]
@CrossR Didn't work for me, Im so sure it is that I broke something I suppose I have to purge all oni dirictories and have a fresh install. You have the cleanest dotfiles I have ever seen btw

**Comment by youssoftaha** [comment]
Not working. I have no Idea why. Not very fruitful, I know.
