### ISSUE TITLE
Closing oni with X button leaves swap file even when saved

### ISSUE THREAD

**Issue by sullyj3** [onivim/oni#2581]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):**
**Operating System:** Windows 7 

**Issue:** "X" button for window leaves behind a swap file, even when the file has not been edited since save.

**Expected behavior:** Similar to typing :q with only 1 file open, window should close, and should remove swap file when buffer is the same as the file on disk.

**Steps to reproduce:** Save any file with :w, click the x button, reopen oni, and :e the same file.

**Comment by CrossR** [comment]
I think this is actually the same as these early tickets : https://github.com/onivim/oni/issues/264 & https://github.com/onivim/oni/issues/670.

If we have a prompt on close, that should include a clean up step on closing. I think currently, our default config disables swap files, but that is a bandaid rather than a fix.

I'll close this out, since the other tickets seem to cover this, and the save on close actually has a bounty on it, so if someone does pick that up, its good to have it contained so we remember to give the bounty out!
