### ISSUE TITLE
Generate hero video from automation

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#309]
- Single demonstration gif / youtube video
- Move to majority of usage / instructions to `docs` folder
- Publish `docs` folder with gitbooks

**Comment by bert88sta** [comment]
If you could list out fairly explicitly what you want to be in the video I'd be happy to do that. I might need some of the shortcuts listed out .

**Comment by keforbes** [comment]
I was thinking the same thing, a video should be pretty easy for us to help out with.  Here's the script that I've been running through my head.  Feel free to do it yourself if it makes sense.  I'm thinking this would be a youtube video since it's a bit much for a single gif.

1. Start with Oni launched but no file loaded
2. Use File -> Open dialog to open a Typescript file
3. Move the cursor over an item to show the QuickInfo popup
4. Start editing the file to show the autocompletion popup
5. Hit `Ctrl+P` to open the Fuzzy Finder
6. Type a couple characters to show the filter working, select another Typescript file
7. Edit the file and introduce an error
8. Save the file to show the error popup
9. Edit the file again (somewhere else) and demo the live evaluation
10. Move the cursor over one of the methods in the file
11. Hit `Ctrl+Shift+P` to bring up the command palette
12. Type characters (to show filtering) and select Find All References
13. Select one of the references in a different file and hit `<Enter>` to jump to that file

In my mind, this progresses gradually from features you'd expect to find in a text editor to features that you'd find in an IDE.  It introduces concepts in a simple way first (Fuzzy Finder, error popup) before showing those concepts expanded into further uses (Command Palette, live evaluation) and ends with a totally IDE feature of Find All References.  And yes, I've spent too much time today thinking about this.  I think it captures all the fancy features in Oni though.

**Comment by extr0py** [comment]
Excellent, having the video would be a huge help. The script looks great to me, as it highlights all of the main features we have in Oni today that work out of the box, progressively. It consolidates all the items in the gifs to a single script.

I'm also thinking it'd be helpful to have a quick animated gif on the github landing page - maybe a subset, so just steps 1-6 - completion is probably the most compelling feature we have today. Thanks for thinking about this!

@bert88sta - would you be up for making the gif & video? We could create an issue specific to that, so I can get a bounty to you.
