### ISSUE TITLE
Language Client: Implement syntax highlighting

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#379]
Language protocol-supported syntax highlighting can be built using the documentSymbol request:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_documentSymbol

**Comment by jordwalke** [comment]
Is there a really good example of an editor using this without a Flash of Unstlyed Content or other lags? Does VSCode currently use this? Does going out of process make performance more difficult? I'm not skeptical, just curious.

**Comment by extr0py** [comment]
VSCode actually does this - but for large files there is a large flash of unstyled content. My plan right now is to leverage the Vim syntax highlighting for fixed items - like keywords, block styling, strings, comments, etc - and use the `documentSymbol` request for more dynamic items, like variable names.

But ya, as soon as you go out of process, you always incur some latency - so you get that flash of unstyled content. The variable name highlighting is pretty useful IMO - but there could be a setting to disable it if it is too distracting. There are also ways we can look at optimizing the performance, too, across the pipeline in various ways (for using IPC vs stdio, to only requesting symbols for the active 'window', pre-emptively loading symbols for a doc, etc). It seems doable to minimize this, since it's not really noticeable in VSCode after the initial "flash".

**Comment by bryphe** [comment]
This is partially implemented via TextMate grammars, behind the `experimental.editor.textMateHighlighting.enabled` flag here: https://github.com/onivim/oni/wiki/Configuration#textmate-highlighting

**Comment by bryphe** [comment]
Textmate highlighting is now enabled by default with #1639
