### ISSUE TITLE
Windows - Installer: Uninstall does not remove entire Oni folder

### ISSUE THREAD

**Issue by bryphe** [onivim/oni#512]
- Uninstall does not remove Oni folder completely
- Reinstall should clean up folder - sometimes stale dependencies / libraries cause problems.

**Comment by extr0py** [comment]
Workaround is to manually uninstall Oni on Windows.

**Comment by CrossR** [comment]
Under what context does this happen?

So far, I've not had any issues with the Oni folder not being deleted, I've been uninstalling and reinstalling like crazy whilst messing with reg keys, and the only time I hit this was because I was attempting to uninstall whilst I had Oni running.

It looks like Inno has a way of checking if the process is running at uninstall time, so I could look at adding that?

**Comment by extr0py** [comment]
> It looks like Inno has a way of checking if the process is running at uninstall time, so I could look at adding that?

Ah ya, I just tried again and uninstall worked fine. I think you're right - it must've been I had an active process. 

Checking if the process is running sounds like a good solution!

**Comment by bryphe** [comment]
Since we haven't had any reports for this, I'll go ahead and close it out.
