### ISSUE TITLE
Hidden buffers are shown in buffer tabline

### ISSUE THREAD

**Issue by Bretley** [onivim/oni#591]
I have a custom vimscript function that I use to effectively make a "popup" terminal show up.

```
let g:term_buf = 0
function! Term_toggle()
  if g:term_buf == bufnr("")
    setlocal bufhidden=hide
    hide
  else
    botright 15new
    try
      exec "buffer ".g:term_buf
    catch
      term
      let g:term_buf = bufnr("")
    endtry
    startinsert!
  endif
endfunction
```

This causes a new "no name" tab to appear, but it isn't accessible, I.e. clicking on it doesn't take me to an empty buffer, and I can't exit it by clicking on it.

**Comment by extr0py** [comment]
Thanks for logging this @bert88sta ! Ya, sounds like we're not handling hidden buffers correctly - they shouldn't be shown in tabs.

**Comment by extr0py** [comment]
@bert88sta - just curious - is there a reason why you are setting the buffer to hidden in this case?

**Comment by cyansprite** [comment]
I do something similar it's so that if I use something that switches through buffer it hides the ones that are hidden, that way I don't switch through my buffers and accidentally open my terminal instead of a file I'm trying to get to.

**Comment by cyansprite** [comment]
in ./browser/src/UI/components/Tabs.tsx
```ts
<div className="corner" onClick={props.onClickName}></div>
```

that way you don't have to click directly on the name but you can click the corner without an X.
This is an issue I ran into with things with short names.

in browser/src/neovim/Buffer.ts
```ts
public getOption(optionName: string): Promise<any> {
     return this._session.request<any>("nvim_buf_get_option", [this._bufferReference, optionName])
}
```

that way we can check buffer var of hidden/listed.
I think hidden might be fine to leave in the tabs since I jump from buffers a lot and don't use tabs, but don't show listed.

**Comment by extr0py** [comment]
Good call! The tab issue is pretty straightforward, I'll open a PR for that.

For the buffers - we'll have to figure out the timing of when we make that request (seems like we'd have to check it for all buffers too). It would be nice to have this metadata for the buffers available in the Redux store, so the UI could treat it appropriately -

**Comment by bryphe** [comment]
Unfortunately I realized to support some of the scenarios - like being able to navigate away from a file when it has edits, we'd need to use the `set hidden` option. This is important for gestures like go-to definition, applying refactorings across a workspace, etc. Without `set hidden`, we have to use `e!`, which clears pending edits (super annoying with go-to definition - #778).

So in order to accomplish those scenarios - we'll need to specify the `set hidden` option by default. However, perhaps we can figure out another way to filter out the relevant buffers from the tabline?

Let me know if you have any ideas here.

**Comment by Bretley** [comment]
@bryphe as far as I can tell, this has been resolved by the last set of merges on master. Unless you need this open for something you'd still like to implement it, you can close this

**Comment by bryphe** [comment]
This scenario works better now that `tabs.mode` - `'tabs'` is the default setting, with #1667. I'll close this out.
