### ISSUE TITLE
Generic Fuzzy Finder/Quickopen Menu 

### ISSUE THREAD

**Issue by Bretley** [onivim/oni#776]
Hi, I think with a little bit of tweaking the QuickOpen and Fuzzy Finder could be really powerful as a config tool. 

I'm imagining the user giving us an opening action (i.e some keybinding), a list of things or a way to get this list, and a behavior once an item is selected. If you know what helm is, you'll know that it's every Emacs user's favorite thing that vim can't do.

I think if this were done, we'd have a solid way to replace wildmenu

**Comment by Bretley** [comment]
Ex:

Open on colon in normal mode
match to vim commands
when selected,  pass to neovim

**Comment by bryphe** [comment]
Yes, definitely in-line with what I'm thinking about! Thanks for opening this, @Bretley 

I think there are a couple of items here:
- __Generalizing the 'menu'__ - I've actually started this here in #764. This creates a `menu` API - so you could even do something like this in your config:

```
oni.input.bind("<c-enter>", () => {
    const myMenu = oni.menu.create()
    myMenu.setItems([{label: "Option 1"}, {label: "Option2"}])
    myMenu.onItemSelected.subscribe((selectedOption) => alert(selectedOption))
    myMenu.show()
})
```

This would show a menu with 'Option 1' and 'Option 2', and then an alert once it is selected... but it could be generalized to do much more interesting things, based on the items collection and the action on selection.

The remaining part of that change is factoring over the existing QuickOpen behavior to that model - and supporting asynchronous / streaming results at the same time (this new API surface is better suited for it, since as we get new results from the finder program, we can just tack them onto `setItems`). 

- __Additional modes__ - one thing that was really interesting in the discussion for #635 was the idea of _prefix support_ - `:` for vim command mode, `&` to show available buffers, `#` for symbol search, etc. I think this is a cool idea, and could be backed by the generalization of the `menu` concept above.

Do you know any good youtube videos or reading material on helm? I haven't used Emacs too much, but am interested in learning more - I think Oni is philosophically closer to Emacs than Vim, in terms of the extensibility / programmability model, so I've been spending a little time learning more about the cool things Emacs has (like magit, org-mode, etc) for inspiration 😄

**Comment by Bretley** [comment]
https://tuhdo.github.io/helm-intro.html

Helm is basically a fzf interface to literally anything you can do in emacs. It's *really* awesome.

**Comment by CrossR** [comment]
I'd consider the Generic fuzzy finder aspect of this complete, I know I'm using a few custom fuzzy finder menus!

Woud it be worth opening a second issue specific to the prefix support, if we still think its relevant, and closing this issue?

**Comment by bryphe** [comment]
> I'd consider the Generic fuzzy finder aspect of this complete, I know I'm using a few custom fuzzy finder menus!

Agreed! Ya, your config has some great examples! 😄 

> Woud it be worth opening a second issue specific to the prefix support, if we still think its relevant, and closing this issue?

I think it's okay to close for now, but we can revive that if we feel it would be helpful. A clear use case would be helpful to motivate it, anyway.

I'll close this for now, but @Bretley let us know if you have any other ideas!
