### ISSUE TITLE
Autocomplete opens from top when opening via <C-n>

### ISSUE THREAD

**Issue by Bretley** [onivim/oni#895]
<img width="846" alt="screen shot 2017-11-08 at 2 12 57 pm" src="https://user-images.githubusercontent.com/8421641/32569400-03b5db92-c48f-11e7-9ae5-fa2e058df914.png">

It's fine after i type a little bit but when it initially comes up it's in the wrong spot

**Comment by bryphe** [comment]
@badosu also hit this issue in #958

**Comment by bryphe** [comment]
Looks like `<C-n>` menu is opening upwards, because of the cursor movement we get during redraw.

What's happening is, when the popupmenu opens, Neovim moves the cursor down to the command line to render text / info about the matches. We measure the popupmenu from that location, see that it's close to the bottom, and open upward. Then, the cursor moves back, but we don't re-measure the completion menu.

The best fix here IMO is to leverage the `ext_cmdline` and `ext_wildmenu` so we get less 'noise' with the cursor movement there. Need to check and see if that prevents the match message from showing, though.

**Comment by bryphe** [comment]
This should be addressed now by #1268
