### ISSUE TITLE
Confusion about this project.

### ISSUE THREAD

**Issue by IvRRimum** [onivim/oni#906]
By reading thought the docs it's not really understandable if oni is backwards compatible with neovim plugins?

For example i like to use fugitive and ack plugins for neovim. When following your guide and just git cloning them in ~/oni/plugins they don't work in oni.

Just wanted this clarification.

**Comment by IvRRimum** [comment]
However some plugins work. Like CTRLP plugin works as intended.

**Comment by CrossR** [comment]
Yep, Oni is (for the most part) completely backwards compatible with NeoVim plugins.

There has been a few instances where some of the plugins UIs have not been correctly rendered or similar, but in general every vim plugin that I use has worked perfectly.

I do think the Docs for this could be tidied up a bit since it is confusing, but my understanding is as follows: If you want, you can use the default neovim plugin folders, or you can use the specific oni folder and then that plugin will only be loaded in Oni.
If you are already a neovim user, then you are fine to continue using your existing plugin folders.

My dotfiles are available [here](https://github.com/CrossR/dotfiles/blob/master/neovim/.config/nvim/init.vim), so gives you an idea of the plugins I use with Oni fine, as well as a slightly different way of specifying Oni specific plugins.

**Comment by TalAmuyal** [comment]
Closing this issue since the question is answered.
@IvRRimum, if you have any more questions or have some suggestions, please reopen this issue, open a new one or ask at Gitter (https://gitter.im/onivim/Lobby).

Cheers :)
