### ISSUE TITLE
Vendoring Python

### ISSUE THREAD

**Issue by jordwalke** [onivim/oni#936]
Some people who have tried to get setup with `Oni` run into issues with their python installation. Configuring python is a nightmare for people who don't use python daily. Is it possible/easy to vendor Python into Oni?

**Comment by bryphe** [comment]
Thanks for inspiring people to try out Oni (and helping them get set up)! Looks like we had a record number of downloads today.

> Some people who have tried to get setup with Oni run into issues with their python installation. 

Is this the same issue as #868? It seems like there is a specific issue on OSX, where if the `python` or `python3` executable is in `/usr/local/bin`, there'd be issues loading the python host (in the worst way, Oni would be unusable).

That particular issue is fixed with #924 - I'm planning on cutting a release with this fix on Wednesday. (The root cause was that Oni wasn't getting the full set of environment variables, and this caused problems with Neovim initializing the python provider). We're also looking at solving this in a more general way by leveraging [shell-env](https://www.npmjs.com/package/shell-env)

What's interesting is, prior to the fix in #924 , Oni worked fine on OSX if there was _no python binary available_, and also if `python` or `python3` was available in `/usr/bin`... but would have problems if it was somewhere else, like `usr/local/bin`.

Alternatively - are they hitting this issue because they want to use a plugin that depends on python, like UltiSnips? And having difficulty configuring it?

> Configuring python is a nightmare for people who don't use python daily. 

This is so true! I'm trying to stay away from packaging Python, if I can help it... Especially on Windows.

**Comment by jordwalke** [comment]
Sounds like you've got a handle on things then. If packaging Python is out of the question, I'll close this issue. (I mean, I can't blame you - there's no way I would ever attempt that).

**Comment by bryphe** [comment]
👍 #868 should be fixed now in [0.2.17](https://github.com/onivim/oni/releases). Will be interested to see if there are still configurations that have issues.

**Comment by chenglou** [comment]
Fixed for me! =D

**Comment by bryphe** [comment]
Awesome, great to hear! Thanks @Akin909 for all your work on #924 & #1066 to fix these issues.
